# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guilh\Desktop\NewPharmaExperience\npx_mock\src\GUI\ClienteInput.ui'
#
# Created: Mon Apr  2 23:38:42 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ClienteFrame(QtGui.QWidget):
    def __init__(self, master):
        QtGui.QWidget.__init__(self,master)
        self.gridLayout_10 = QtGui.QGridLayout(self)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.ClienteFrame1 = QtGui.QFrame(self)
        self.ClienteFrame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ClienteFrame1.setFrameShadow(QtGui.QFrame.Raised)
        self.ClienteFrame1.setObjectName("ClienteFrame1")
        self.gridLayout_9 = QtGui.QGridLayout(self.ClienteFrame1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.GroupBox = QtGui.QGroupBox(self.ClienteFrame1)
        self.GroupBox.setTitle("")
        self.GroupBox.setObjectName("GroupBox")
        self.gridLayout_8 = QtGui.QGridLayout(self.GroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ClienteFrame2 = QtGui.QFrame(self.GroupBox)
        self.ClienteFrame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ClienteFrame2.setFrameShadow(QtGui.QFrame.Raised)
        self.ClienteFrame2.setObjectName("ClienteFrame2")
        self.gridLayout_4 = QtGui.QGridLayout(self.ClienteFrame2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_5 = QtGui.QWidget(self.ClienteFrame2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.TelefoneLabel = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TelefoneLabel.sizePolicy().hasHeightForWidth())
        self.TelefoneLabel.setSizePolicy(sizePolicy)
        self.TelefoneLabel.setObjectName("TelefoneLabel")
        self.gridLayout_6.addWidget(self.TelefoneLabel, 0, 0, 1, 1)
        self.CelularLabel = QtGui.QLabel(self.widget_5)
        self.CelularLabel.setObjectName("CelularLabel")
        self.gridLayout_6.addWidget(self.CelularLabel, 0, 2, 1, 1)
        self.CelularEntry = QtGui.QLineEdit(self.widget_5)
        self.CelularEntry.setMaxLength(9)
        self.CelularEntry.setObjectName("CelularEntry")
        self.gridLayout_6.addWidget(self.CelularEntry, 0, 3, 1, 1)
        self.TelefoneEntry = QtGui.QLineEdit(self.widget_5)
        self.TelefoneEntry.setMaxLength(9)
        self.TelefoneEntry.setObjectName("TelefoneEntry")
        self.gridLayout_6.addWidget(self.TelefoneEntry, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(500, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_5, 8, 0, 1, 1)
        self.widget_4 = QtGui.QWidget(self.ClienteFrame2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.NomeLabel = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NomeLabel.sizePolicy().hasHeightForWidth())
        self.NomeLabel.setSizePolicy(sizePolicy)
        self.NomeLabel.setObjectName("NomeLabel")
        self.gridLayout_5.addWidget(self.NomeLabel, 0, 0, 1, 1)
        self.NomeEntry = QtGui.QLineEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NomeEntry.sizePolicy().hasHeightForWidth())
        self.NomeEntry.setSizePolicy(sizePolicy)
        self.NomeEntry.setObjectName("NomeEntry")
        self.gridLayout_5.addWidget(self.NomeEntry, 0, 1, 1, 1)
        self.CPFLabel = QtGui.QLabel(self.widget_4)
        self.CPFLabel.setObjectName("CPFLabel")
        self.gridLayout_5.addWidget(self.CPFLabel, 0, 2, 1, 1)
        self.CPFEntry = QtGui.QLineEdit(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPFEntry.sizePolicy().hasHeightForWidth())
        self.CPFEntry.setSizePolicy(sizePolicy)
        self.CPFEntry.setMaxLength(11)
        self.CPFEntry.setObjectName("CPFEntry")
        self.gridLayout_5.addWidget(self.CPFEntry, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_4, 2, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.ClienteFrame2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Salvar_Button = QtGui.QPushButton(self.widget_2)
        self.Salvar_Button.setObjectName("Salvar_Button")
        self.gridLayout_2.addWidget(self.Salvar_Button, 0, 1, 1, 1)
        self.Cancelar_Button = QtGui.QPushButton(self.widget_2)
        self.Cancelar_Button.setObjectName("Cancelar_Button")
        self.gridLayout_2.addWidget(self.Cancelar_Button, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 9, 0, 1, 1)
        self.widget_3 = QtGui.QWidget(self.ClienteFrame2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CEPLabel = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CEPLabel.sizePolicy().hasHeightForWidth())
        self.CEPLabel.setSizePolicy(sizePolicy)
        self.CEPLabel.setObjectName("CEPLabel")
        self.gridLayout_3.addWidget(self.CEPLabel, 2, 0, 1, 1)
        self.NumLabel = QtGui.QLabel(self.widget_3)
        self.NumLabel.setObjectName("NumLabel")
        self.gridLayout_3.addWidget(self.NumLabel, 0, 2, 1, 1)
        self.NumEntry = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumEntry.sizePolicy().hasHeightForWidth())
        self.NumEntry.setSizePolicy(sizePolicy)
        self.NumEntry.setMaxLength(10)
        self.NumEntry.setObjectName("NumEntry")
        self.gridLayout_3.addWidget(self.NumEntry, 0, 3, 1, 1)
        self.RuaLabel = QtGui.QLabel(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RuaLabel.sizePolicy().hasHeightForWidth())
        self.RuaLabel.setSizePolicy(sizePolicy)
        self.RuaLabel.setObjectName("RuaLabel")
        self.gridLayout_3.addWidget(self.RuaLabel, 0, 0, 1, 1)
        self.CompLabel = QtGui.QLabel(self.widget_3)
        self.CompLabel.setObjectName("CompLabel")
        self.gridLayout_3.addWidget(self.CompLabel, 2, 2, 1, 1)
        self.CompEntry = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompEntry.sizePolicy().hasHeightForWidth())
        self.CompEntry.setSizePolicy(sizePolicy)
        self.CompEntry.setMaxLength(30)
        self.CompEntry.setObjectName("CompEntry")
        self.gridLayout_3.addWidget(self.CompEntry, 2, 3, 1, 1)
        self.RuaEntry = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RuaEntry.sizePolicy().hasHeightForWidth())
        self.RuaEntry.setSizePolicy(sizePolicy)
        self.RuaEntry.setObjectName("RuaEntry")
        self.gridLayout_3.addWidget(self.RuaEntry, 0, 1, 1, 1)
        self.CEPEntry = QtGui.QLineEdit(self.widget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CEPEntry.sizePolicy().hasHeightForWidth())
        self.CEPEntry.setSizePolicy(sizePolicy)
        self.CEPEntry.setMaxLength(8)
        self.CEPEntry.setObjectName("CEPEntry")
        self.gridLayout_3.addWidget(self.CEPEntry, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 5, 0, 1, 1)
        self.InfoPesso = QtGui.QLabel(self.ClienteFrame2)
        self.InfoPesso.setObjectName("InfoPesso")
        self.gridLayout_4.addWidget(self.InfoPesso, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.ClienteFrame2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 7, 0, 1, 6)
        self.Contato = QtGui.QLabel(self.ClienteFrame2)
        self.Contato.setObjectName("Contato")
        self.gridLayout_4.addWidget(self.Contato, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.ClienteFrame2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 4, 0, 1, 6)
        self.line_3 = QtGui.QFrame(self.ClienteFrame2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 1, 0, 1, 6)
        self.Endereco = QtGui.QLabel(self.ClienteFrame2)
        self.Endereco.setObjectName("Endereco")
        self.gridLayout_4.addWidget(self.Endereco, 3, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 10, 0, 1, 6)
        self.gridLayout_8.addWidget(self.ClienteFrame2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.GroupBox, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.ClienteFrame1, 0, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, ClienteFrame):
        ClienteFrame.setWindowTitle(QtGui.QApplication.translate("ClienteFrame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.TelefoneLabel.setText(QtGui.QApplication.translate("ClienteFrame", "Telefone", None, QtGui.QApplication.UnicodeUTF8))
        self.CelularLabel.setText(QtGui.QApplication.translate("ClienteFrame", "Celular", None, QtGui.QApplication.UnicodeUTF8))
        self.NomeLabel.setText(QtGui.QApplication.translate("ClienteFrame", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.CPFLabel.setText(QtGui.QApplication.translate("ClienteFrame", "CPF", None, QtGui.QApplication.UnicodeUTF8))
        self.Salvar_Button.setText(QtGui.QApplication.translate("ClienteFrame", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.Cancelar_Button.setText(QtGui.QApplication.translate("ClienteFrame", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.CEPLabel.setText(QtGui.QApplication.translate("ClienteFrame", "CEP", None, QtGui.QApplication.UnicodeUTF8))
        self.NumLabel.setText(QtGui.QApplication.translate("ClienteFrame", "Número", None, QtGui.QApplication.UnicodeUTF8))
        self.RuaLabel.setText(QtGui.QApplication.translate("ClienteFrame", "Rua", None, QtGui.QApplication.UnicodeUTF8))
        self.CompLabel.setText(QtGui.QApplication.translate("ClienteFrame", "Complemento", None, QtGui.QApplication.UnicodeUTF8))
        self.InfoPesso.setText(QtGui.QApplication.translate("ClienteFrame", "Informações Pessoais:", None, QtGui.QApplication.UnicodeUTF8))
        self.Contato.setText(QtGui.QApplication.translate("ClienteFrame", "Contato:", None, QtGui.QApplication.UnicodeUTF8))
        self.Endereco.setText(QtGui.QApplication.translate("ClienteFrame", "Endereço:", None, QtGui.QApplication.UnicodeUTF8))

import npx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ClienteFrame = QtGui.QFrame()
    ui = Ui_ClienteFrame()
    ui.setupUi(ClienteFrame)
    ClienteFrame.show()
    sys.exit(app.exec_())
