# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guilh\Desktop\NewPharmaExperience\npx_mock\src\GUI\DistInput.ui'
#
# Created: Mon Apr  2 22:46:30 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DistInput(QtGui.QWidget):
    def __init__(self, master):
        QtGui.QWidget.__init__(self,master)
        self.gridLayout_4 = QtGui.QGridLayout(self)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LabFrame = QtGui.QFrame(self)
        self.LabFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.LabFrame.setObjectName("LabFrame")
        self.gridLayout_2 = QtGui.QGridLayout(self.LabFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TitleLabel = QtGui.QLabel(self.LabFrame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_2.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.LogoLabel = QtGui.QLabel(self.LabFrame)
        self.LogoLabel.setObjectName("LogoLabel")
        self.gridLayout_2.addWidget(self.LogoLabel, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.LabFrame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.ButtonWidget = QtGui.QWidget(self.groupBox)
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.ButtonWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CancelarButton = QtGui.QPushButton(self.ButtonWidget)
        self.CancelarButton.setObjectName("CancelarButton")
        self.gridLayout_5.addWidget(self.CancelarButton, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.SalvarButton = QtGui.QPushButton(self.ButtonWidget)
        self.SalvarButton.setObjectName("SalvarButton")
        self.gridLayout_5.addWidget(self.SalvarButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.ButtonWidget, 1, 0, 1, 1)
        self.InputWidget = QtGui.QWidget(self.groupBox)
        self.InputWidget.setObjectName("InputWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.InputWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EnderLabel_3 = QtGui.QLabel(self.InputWidget)
        self.EnderLabel_3.setObjectName("EnderLabel_3")
        self.gridLayout_3.addWidget(self.EnderLabel_3, 3, 2, 1, 1)
        self.EnderLabel_4 = QtGui.QLabel(self.InputWidget)
        self.EnderLabel_4.setObjectName("EnderLabel_4")
        self.gridLayout_3.addWidget(self.EnderLabel_4, 5, 0, 1, 1)
        self.CNPJLabel = QtGui.QLabel(self.InputWidget)
        self.CNPJLabel.setObjectName("CNPJLabel")
        self.gridLayout_3.addWidget(self.CNPJLabel, 1, 2, 1, 1)
        self.EnderLabel_2 = QtGui.QLabel(self.InputWidget)
        self.EnderLabel_2.setObjectName("EnderLabel_2")
        self.gridLayout_3.addWidget(self.EnderLabel_2, 5, 2, 1, 1)
        self.NameLabel = QtGui.QLabel(self.InputWidget)
        self.NameLabel.setObjectName("NameLabel")
        self.gridLayout_3.addWidget(self.NameLabel, 1, 0, 1, 1)
        self.EnderEntry = QtGui.QLineEdit(self.InputWidget)
        self.EnderEntry.setMaximumSize(QtCore.QSize(16777215, 500))
        self.EnderEntry.setObjectName("EnderEntry")
        self.gridLayout_3.addWidget(self.EnderEntry, 3, 1, 1, 1)
        self.NameEntry = QtGui.QLineEdit(self.InputWidget)
        self.NameEntry.setMaximumSize(QtCore.QSize(16777215, 500))
        self.NameEntry.setObjectName("NameEntry")
        self.gridLayout_3.addWidget(self.NameEntry, 1, 1, 1, 1)
        self.Email2Label = QtGui.QLabel(self.InputWidget)
        self.Email2Label.setObjectName("Email2Label")
        self.gridLayout_3.addWidget(self.Email2Label, 8, 0, 1, 1)
        self.Email1Entry = QtGui.QLineEdit(self.InputWidget)
        self.Email1Entry.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Email1Entry.setObjectName("Email1Entry")
        self.gridLayout_3.addWidget(self.Email1Entry, 7, 1, 1, 1)
        self.Email1Label = QtGui.QLabel(self.InputWidget)
        self.Email1Label.setObjectName("Email1Label")
        self.gridLayout_3.addWidget(self.Email1Label, 7, 0, 1, 1)
        self.EnderLabel = QtGui.QLabel(self.InputWidget)
        self.EnderLabel.setObjectName("EnderLabel")
        self.gridLayout_3.addWidget(self.EnderLabel, 3, 0, 1, 1)
        self.EnderEntry_3 = QtGui.QLineEdit(self.InputWidget)
        self.EnderEntry_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.EnderEntry_3.setObjectName("EnderEntry_3")
        self.gridLayout_3.addWidget(self.EnderEntry_3, 5, 1, 1, 1)
        self.Email2Entry = QtGui.QLineEdit(self.InputWidget)
        self.Email2Entry.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Email2Entry.setObjectName("Email2Entry")
        self.gridLayout_3.addWidget(self.Email2Entry, 8, 1, 1, 1)
        self.FaxLabel = QtGui.QLabel(self.InputWidget)
        self.FaxLabel.setObjectName("FaxLabel")
        self.gridLayout_3.addWidget(self.FaxLabel, 11, 0, 1, 1)
        self.FaxEntry = QtGui.QLineEdit(self.InputWidget)
        self.FaxEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FaxEntry.setObjectName("FaxEntry")
        self.gridLayout_3.addWidget(self.FaxEntry, 11, 1, 1, 1)
        self.Phone1Entry = QtGui.QLineEdit(self.InputWidget)
        self.Phone1Entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Phone1Entry.setObjectName("Phone1Entry")
        self.gridLayout_3.addWidget(self.Phone1Entry, 7, 3, 1, 1)
        self.Phone2Entry = QtGui.QLineEdit(self.InputWidget)
        self.Phone2Entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Phone2Entry.setObjectName("Phone2Entry")
        self.gridLayout_3.addWidget(self.Phone2Entry, 8, 3, 1, 1)
        self.Phone2Label = QtGui.QLabel(self.InputWidget)
        self.Phone2Label.setObjectName("Phone2Label")
        self.gridLayout_3.addWidget(self.Phone2Label, 8, 2, 1, 1)
        self.Phone1Label = QtGui.QLabel(self.InputWidget)
        self.Phone1Label.setObjectName("Phone1Label")
        self.gridLayout_3.addWidget(self.Phone1Label, 7, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.InputWidget)
        self.comboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 5, 3, 1, 1)
        self.EnderEntry_2 = QtGui.QLineEdit(self.InputWidget)
        self.EnderEntry_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.EnderEntry_2.setObjectName("EnderEntry_2")
        self.gridLayout_3.addWidget(self.EnderEntry_2, 3, 3, 1, 1)
        self.CNPJEntry = QtGui.QLineEdit(self.InputWidget)
        self.CNPJEntry.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CNPJEntry.setObjectName("CNPJEntry")
        self.gridLayout_3.addWidget(self.CNPJEntry, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.InputWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.LabFrame, 0, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, DistInput):
        DistInput.setWindowTitle(QtGui.QApplication.translate("DistInput", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.TitleLabel.setText(QtGui.QApplication.translate("DistInput", "<html><head/><body><p align=\"center\">Cadastro de Distribuidores</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LogoLabel.setText(QtGui.QApplication.translate("DistInput", "<html><head/><body><p><img src=\":/NPX ICO/clinic (2).png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelarButton.setText(QtGui.QApplication.translate("DistInput", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.SalvarButton.setText(QtGui.QApplication.translate("DistInput", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.EnderLabel_3.setText(QtGui.QApplication.translate("DistInput", "Número", None, QtGui.QApplication.UnicodeUTF8))
        self.EnderLabel_4.setText(QtGui.QApplication.translate("DistInput", "Cidade", None, QtGui.QApplication.UnicodeUTF8))
        self.CNPJLabel.setText(QtGui.QApplication.translate("DistInput", "CNPJ", None, QtGui.QApplication.UnicodeUTF8))
        self.EnderLabel_2.setText(QtGui.QApplication.translate("DistInput", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.NameLabel.setText(QtGui.QApplication.translate("DistInput", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.Email2Label.setText(QtGui.QApplication.translate("DistInput", "E-mail 2", None, QtGui.QApplication.UnicodeUTF8))
        self.Email1Label.setText(QtGui.QApplication.translate("DistInput", "E-mail 1", None, QtGui.QApplication.UnicodeUTF8))
        self.EnderLabel.setText(QtGui.QApplication.translate("DistInput", "Rua", None, QtGui.QApplication.UnicodeUTF8))
        self.FaxLabel.setText(QtGui.QApplication.translate("DistInput", "Fax", None, QtGui.QApplication.UnicodeUTF8))
        self.Phone2Label.setText(QtGui.QApplication.translate("DistInput", "Telefone 2", None, QtGui.QApplication.UnicodeUTF8))
        self.Phone1Label.setText(QtGui.QApplication.translate("DistInput", "Telefone 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("DistInput", "AC", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("DistInput", "AL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("DistInput", "AP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("DistInput", "AM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("DistInput", "BA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("DistInput", "CE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("DistInput", "DF", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("DistInput", "ES", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("DistInput", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("DistInput", "MA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(10, QtGui.QApplication.translate("DistInput", "MT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(11, QtGui.QApplication.translate("DistInput", "MS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(12, QtGui.QApplication.translate("DistInput", "MG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(13, QtGui.QApplication.translate("DistInput", "PA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(14, QtGui.QApplication.translate("DistInput", "PB", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(15, QtGui.QApplication.translate("DistInput", "PR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(16, QtGui.QApplication.translate("DistInput", "PE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(17, QtGui.QApplication.translate("DistInput", "PI", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(18, QtGui.QApplication.translate("DistInput", "RJ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(19, QtGui.QApplication.translate("DistInput", "RN", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(20, QtGui.QApplication.translate("DistInput", "RS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(21, QtGui.QApplication.translate("DistInput", "RO", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(22, QtGui.QApplication.translate("DistInput", "RR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(23, QtGui.QApplication.translate("DistInput", "SC", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(24, QtGui.QApplication.translate("DistInput", "SP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(25, QtGui.QApplication.translate("DistInput", "SE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(26, QtGui.QApplication.translate("DistInput", "TO", None, QtGui.QApplication.UnicodeUTF8))


from src.GUI import npx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DistInput = QtGui.QFrame()
    ui = Ui_DistInput()
    ui.setupUi(DistInput)
    DistInput.show()
    sys.exit(app.exec_())
