# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guilh\Desktop\NewPharmaExperience\npx_mock\src\GUI\InputFrame.ui'
#
# Created: Sun Apr  1 02:03:53 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_InputPage(object):
    def setupUi(self, InputPage):
        InputPage.setObjectName("InputPage")
        InputPage.resize(887, 686)
        InputPage.setFrameShape(QtGui.QFrame.StyledPanel)
        InputPage.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_19 = QtGui.QGridLayout(InputPage)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.InputFrame = QtGui.QFrame(InputPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputFrame.sizePolicy().hasHeightForWidth())
        self.InputFrame.setSizePolicy(sizePolicy)
        self.InputFrame.setMinimumSize(QtCore.QSize(777, 584))
        self.InputFrame.setBaseSize(QtCore.QSize(777, 584))
        self.InputFrame.setAutoFillBackground(True)
        self.InputFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout_14 = QtGui.QGridLayout(self.InputFrame)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.InputTabs = QtGui.QTabWidget(self.InputFrame)
        self.InputTabs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputTabs.sizePolicy().hasHeightForWidth())
        self.InputTabs.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.InputTabs.setPalette(palette)
        self.InputTabs.setAutoFillBackground(True)
        self.InputTabs.setStyleSheet("")
        self.InputTabs.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.InputTabs.setObjectName("InputTabs")
        self.Descricao = QtGui.QWidget()
        self.Descricao.setObjectName("Descricao")
        self.gridLayout = QtGui.QGridLayout(self.Descricao)
        self.gridLayout.setObjectName("gridLayout")
        self.Description_Frame = QtGui.QFrame(self.Descricao)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Description_Frame.sizePolicy().hasHeightForWidth())
        self.Description_Frame.setSizePolicy(sizePolicy)
        self.Description_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.Description_Frame.setAutoFillBackground(True)
        self.Description_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Description_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Description_Frame.setObjectName("Description_Frame")
        self.gridLayout_11 = QtGui.QGridLayout(self.Description_Frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 4, 0, 1, 2)
        self.Descr_Widget2 = QtGui.QWidget(self.Description_Frame)
        self.Descr_Widget2.setObjectName("Descr_Widget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Descr_Widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MedCheckBox_2 = QtGui.QCheckBox(self.Descr_Widget2)
        self.MedCheckBox_2.setChecked(True)
        self.MedCheckBox_2.setObjectName("MedCheckBox_2")
        self.verticalLayout_3.addWidget(self.MedCheckBox_2)
        self.SNGPC_Checkbox = QtGui.QCheckBox(self.Descr_Widget2)
        self.SNGPC_Checkbox.setAutoRepeat(False)
        self.SNGPC_Checkbox.setTristate(False)
        self.SNGPC_Checkbox.setObjectName("SNGPC_Checkbox")
        self.verticalLayout_3.addWidget(self.SNGPC_Checkbox)
        self.Type_ComboBox = QtGui.QComboBox(self.Descr_Widget2)
        self.Type_ComboBox.setObjectName("Type_ComboBox")
        self.Type_ComboBox.addItem("")
        self.Type_ComboBox.addItem("")
        self.Type_ComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.Type_ComboBox)
        self.gridLayout_11.addWidget(self.Descr_Widget2, 0, 1, 1, 1)
        self.Descr_Widget1 = QtGui.QWidget(self.Description_Frame)
        self.Descr_Widget1.setObjectName("Descr_Widget1")
        self.gridLayout_3 = QtGui.QGridLayout(self.Descr_Widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PrinAtiv_Label = QtGui.QLabel(self.Descr_Widget1)
        self.PrinAtiv_Label.setObjectName("PrinAtiv_Label")
        self.gridLayout_3.addWidget(self.PrinAtiv_Label, 4, 0, 1, 1)
        self.PrinAtivSearchButton = QtGui.QPushButton(self.Descr_Widget1)
        self.PrinAtivSearchButton.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.PrinAtivSearchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/NPX ICO/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PrinAtivSearchButton.setIcon(icon)
        self.PrinAtivSearchButton.setObjectName("PrinAtivSearchButton")
        self.gridLayout_3.addWidget(self.PrinAtivSearchButton, 4, 3, 1, 1)
        self.Product_Label_2 = QtGui.QLabel(self.Descr_Widget1)
        self.Product_Label_2.setObjectName("Product_Label_2")
        self.gridLayout_3.addWidget(self.Product_Label_2, 0, 0, 1, 1)
        self.Reg_Label_2 = QtGui.QLabel(self.Descr_Widget1)
        self.Reg_Label_2.setObjectName("Reg_Label_2")
        self.gridLayout_3.addWidget(self.Reg_Label_2, 2, 0, 1, 1)
        self.PrintAtiv_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.PrintAtiv_Entry.setObjectName("PrintAtiv_Entry")
        self.gridLayout_3.addWidget(self.PrintAtiv_Entry, 4, 2, 1, 1)
        self.Product_Entry_2 = QtGui.QLineEdit(self.Descr_Widget1)
        self.Product_Entry_2.setObjectName("Product_Entry_2")
        self.gridLayout_3.addWidget(self.Product_Entry_2, 0, 2, 1, 1)
        self.Reg_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reg_Entry.sizePolicy().hasHeightForWidth())
        self.Reg_Entry.setSizePolicy(sizePolicy)
        self.Reg_Entry.setObjectName("Reg_Entry")
        self.gridLayout_3.addWidget(self.Reg_Entry, 2, 2, 1, 1)
        self.Descr_Label = QtGui.QLabel(self.Descr_Widget1)
        self.Descr_Label.setObjectName("Descr_Label")
        self.gridLayout_3.addWidget(self.Descr_Label, 1, 0, 1, 1)
        self.Desc_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.Desc_Entry.setObjectName("Desc_Entry")
        self.gridLayout_3.addWidget(self.Desc_Entry, 1, 2, 1, 1)
        self.Lab_Label = QtGui.QLabel(self.Descr_Widget1)
        self.Lab_Label.setObjectName("Lab_Label")
        self.gridLayout_3.addWidget(self.Lab_Label, 5, 0, 1, 1)
        self.Lab_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.Lab_Entry.setObjectName("Lab_Entry")
        self.gridLayout_3.addWidget(self.Lab_Entry, 5, 2, 1, 1)
        self.Fabr_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.Fabr_Entry.setEnabled(False)
        self.Fabr_Entry.setObjectName("Fabr_Entry")
        self.gridLayout_3.addWidget(self.Fabr_Entry, 6, 2, 1, 1)
        self.Fabr_Label = QtGui.QLabel(self.Descr_Widget1)
        self.Fabr_Label.setEnabled(False)
        self.Fabr_Label.setObjectName("Fabr_Label")
        self.gridLayout_3.addWidget(self.Fabr_Label, 6, 0, 1, 1)
        self.LabSearchButton = QtGui.QPushButton(self.Descr_Widget1)
        self.LabSearchButton.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.LabSearchButton.setText("")
        self.LabSearchButton.setIcon(icon)
        self.LabSearchButton.setObjectName("LabSearchButton")
        self.gridLayout_3.addWidget(self.LabSearchButton, 5, 3, 1, 1)
        self.FabrSearchButton = QtGui.QPushButton(self.Descr_Widget1)
        self.FabrSearchButton.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.FabrSearchButton.setText("")
        self.FabrSearchButton.setIcon(icon)
        self.FabrSearchButton.setObjectName("FabrSearchButton")
        self.gridLayout_3.addWidget(self.FabrSearchButton, 6, 3, 1, 1)
        self.gridLayout_11.addWidget(self.Descr_Widget1, 0, 0, 1, 1)
        self.Descr_Widget3 = QtGui.QWidget(self.Description_Frame)
        self.Descr_Widget3.setObjectName("Descr_Widget3")
        self.gridLayout_10 = QtGui.QGridLayout(self.Descr_Widget3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Tab2Search = QtGui.QPushButton(self.Descr_Widget3)
        self.Tab2Search.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.Tab2Search.setText("")
        self.Tab2Search.setIcon(icon)
        self.Tab2Search.setObjectName("Tab2Search")
        self.gridLayout_10.addWidget(self.Tab2Search, 2, 2, 1, 1)
        self.Tab3Search = QtGui.QPushButton(self.Descr_Widget3)
        self.Tab3Search.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.Tab3Search.setText("")
        self.Tab3Search.setIcon(icon)
        self.Tab3Search.setObjectName("Tab3Search")
        self.gridLayout_10.addWidget(self.Tab3Search, 3, 2, 1, 1)
        self.TabAux1_Label = QtGui.QLabel(self.Descr_Widget3)
        self.TabAux1_Label.setObjectName("TabAux1_Label")
        self.gridLayout_10.addWidget(self.TabAux1_Label, 1, 0, 1, 1)
        self.TabAux2_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.TabAux2_Entry.setObjectName("TabAux2_Entry")
        self.gridLayout_10.addWidget(self.TabAux2_Entry, 2, 1, 1, 1)
        self.Etiqueta_Label = QtGui.QLabel(self.Descr_Widget3)
        self.Etiqueta_Label.setObjectName("Etiqueta_Label")
        self.gridLayout_10.addWidget(self.Etiqueta_Label, 0, 0, 1, 1)
        self.Tab1Search = QtGui.QPushButton(self.Descr_Widget3)
        self.Tab1Search.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.Tab1Search.setText("")
        self.Tab1Search.setIcon(icon)
        self.Tab1Search.setObjectName("Tab1Search")
        self.gridLayout_10.addWidget(self.Tab1Search, 1, 2, 1, 1)
        self.TabAux3_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.TabAux3_Entry.setObjectName("TabAux3_Entry")
        self.gridLayout_10.addWidget(self.TabAux3_Entry, 3, 1, 1, 1)
        self.TabAux1_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.TabAux1_Entry.setObjectName("TabAux1_Entry")
        self.gridLayout_10.addWidget(self.TabAux1_Entry, 1, 1, 1, 1)
        self.TabAux2_Label = QtGui.QLabel(self.Descr_Widget3)
        self.TabAux2_Label.setObjectName("TabAux2_Label")
        self.gridLayout_10.addWidget(self.TabAux2_Label, 2, 0, 1, 1)
        self.Etiqueta_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.Etiqueta_Entry.setObjectName("Etiqueta_Entry")
        self.gridLayout_10.addWidget(self.Etiqueta_Entry, 0, 1, 1, 1)
        self.TabAux3_Label = QtGui.QLabel(self.Descr_Widget3)
        self.TabAux3_Label.setObjectName("TabAux3_Label")
        self.gridLayout_10.addWidget(self.TabAux3_Label, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.Descr_Widget3, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.Description_Frame, 0, 0, 1, 1)
        self.InputTabs.addTab(self.Descricao, "")
        self.Price = QtGui.QWidget()
        self.Price.setObjectName("Price")
        self.gridLayout_13 = QtGui.QGridLayout(self.Price)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.Price_Frame = QtGui.QFrame(self.Price)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Price_Frame.sizePolicy().hasHeightForWidth())
        self.Price_Frame.setSizePolicy(sizePolicy)
        self.Price_Frame.setAutoFillBackground(True)
        self.Price_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Price_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Price_Frame.setObjectName("Price_Frame")
        self.gridLayout_22 = QtGui.QGridLayout(self.Price_Frame)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.PriceWidget2 = QtGui.QWidget(self.Price_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceWidget2.sizePolicy().hasHeightForWidth())
        self.PriceWidget2.setSizePolicy(sizePolicy)
        self.PriceWidget2.setObjectName("PriceWidget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.PriceWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PriceCostType_Label = QtGui.QLabel(self.PriceWidget2)
        self.PriceCostType_Label.setObjectName("PriceCostType_Label")
        self.verticalLayout_2.addWidget(self.PriceCostType_Label)
        self.PriceCostType_ComboBox = QtGui.QComboBox(self.PriceWidget2)
        self.PriceCostType_ComboBox.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.PriceCostType_ComboBox.setObjectName("PriceCostType_ComboBox")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.PriceCostType_ComboBox)
        self.gridLayout_22.addWidget(self.PriceWidget2, 0, 0, 1, 1)
        self.PriceWidget4 = QtGui.QWidget(self.Price_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceWidget4.sizePolicy().hasHeightForWidth())
        self.PriceWidget4.setSizePolicy(sizePolicy)
        self.PriceWidget4.setObjectName("PriceWidget4")
        self.gridLayout_4 = QtGui.QGridLayout(self.PriceWidget4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Discount_Label = QtGui.QLabel(self.PriceWidget4)
        self.Discount_Label.setObjectName("Discount_Label")
        self.gridLayout_4.addWidget(self.Discount_Label, 0, 2, 1, 1)
        self.MaxDiscount_Label = QtGui.QLabel(self.PriceWidget4)
        self.MaxDiscount_Label.setObjectName("MaxDiscount_Label")
        self.gridLayout_4.addWidget(self.MaxDiscount_Label, 1, 2, 1, 1)
        self.CostPrice_Entry = QtGui.QLineEdit(self.PriceWidget4)
        self.CostPrice_Entry.setObjectName("CostPrice_Entry")
        self.gridLayout_4.addWidget(self.CostPrice_Entry, 0, 1, 1, 1)
        self.SellPrice_Label = QtGui.QLabel(self.PriceWidget4)
        self.SellPrice_Label.setObjectName("SellPrice_Label")
        self.gridLayout_4.addWidget(self.SellPrice_Label, 1, 0, 1, 1)
        self.SellPrice_Entry = QtGui.QLineEdit(self.PriceWidget4)
        self.SellPrice_Entry.setObjectName("SellPrice_Entry")
        self.gridLayout_4.addWidget(self.SellPrice_Entry, 1, 1, 1, 1)
        self.CostPrice_Label = QtGui.QLabel(self.PriceWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CostPrice_Label.sizePolicy().hasHeightForWidth())
        self.CostPrice_Label.setSizePolicy(sizePolicy)
        self.CostPrice_Label.setObjectName("CostPrice_Label")
        self.gridLayout_4.addWidget(self.CostPrice_Label, 0, 0, 1, 1)
        self.Discount_Entry = QtGui.QLineEdit(self.PriceWidget4)
        self.Discount_Entry.setObjectName("Discount_Entry")
        self.gridLayout_4.addWidget(self.Discount_Entry, 0, 3, 1, 1)
        self.MaxDiscount_Entry = QtGui.QLineEdit(self.PriceWidget4)
        self.MaxDiscount_Entry.setObjectName("MaxDiscount_Entry")
        self.gridLayout_4.addWidget(self.MaxDiscount_Entry, 1, 3, 1, 1)
        self.ProfitMargin_Label = QtGui.QLabel(self.PriceWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProfitMargin_Label.sizePolicy().hasHeightForWidth())
        self.ProfitMargin_Label.setSizePolicy(sizePolicy)
        self.ProfitMargin_Label.setObjectName("ProfitMargin_Label")
        self.gridLayout_4.addWidget(self.ProfitMargin_Label, 2, 0, 1, 1)
        self.ProfitMargin_Entry = QtGui.QLineEdit(self.PriceWidget4)
        self.ProfitMargin_Entry.setObjectName("ProfitMargin_Entry")
        self.gridLayout_4.addWidget(self.ProfitMargin_Entry, 2, 1, 1, 1)
        self.gridLayout_22.addWidget(self.PriceWidget4, 2, 2, 1, 1)
        self.PriceWidget3 = QtGui.QWidget(self.Price_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceWidget3.sizePolicy().hasHeightForWidth())
        self.PriceWidget3.setSizePolicy(sizePolicy)
        self.PriceWidget3.setObjectName("PriceWidget3")
        self.gridLayout_5 = QtGui.QGridLayout(self.PriceWidget3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.AllowDiscount_Label = QtGui.QLabel(self.PriceWidget3)
        self.AllowDiscount_Label.setObjectName("AllowDiscount_Label")
        self.gridLayout_5.addWidget(self.AllowDiscount_Label, 0, 0, 1, 1)
        self.AllowDiscount_ComboBox = QtGui.QComboBox(self.PriceWidget3)
        self.AllowDiscount_ComboBox.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.AllowDiscount_ComboBox.setObjectName("AllowDiscount_ComboBox")
        self.AllowDiscount_ComboBox.addItem("")
        self.AllowDiscount_ComboBox.addItem("")
        self.gridLayout_5.addWidget(self.AllowDiscount_ComboBox, 1, 0, 1, 1)
        self.gridLayout_22.addWidget(self.PriceWidget3, 0, 2, 1, 1)
        self.PriceWidget1 = QtGui.QWidget(self.Price_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PriceWidget1.sizePolicy().hasHeightForWidth())
        self.PriceWidget1.setSizePolicy(sizePolicy)
        self.PriceWidget1.setObjectName("PriceWidget1")
        self.formLayout_4 = QtGui.QFormLayout(self.PriceWidget1)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.CostLastOrder = QtGui.QLabel(self.PriceWidget1)
        self.CostLastOrder.setObjectName("CostLastOrder")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.CostLastOrder)
        self.CostLastOrder_Entry = QtGui.QLineEdit(self.PriceWidget1)
        self.CostLastOrder_Entry.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.CostLastOrder_Entry.setReadOnly(True)
        self.CostLastOrder_Entry.setObjectName("CostLastOrder_Entry")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.CostLastOrder_Entry)
        self.CostLastOrder_ST = QtGui.QLabel(self.PriceWidget1)
        self.CostLastOrder_ST.setObjectName("CostLastOrder_ST")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.CostLastOrder_ST)
        self.CostLastOrder_ST_Entry = QtGui.QLineEdit(self.PriceWidget1)
        self.CostLastOrder_ST_Entry.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.CostLastOrder_ST_Entry.setReadOnly(True)
        self.CostLastOrder_ST_Entry.setObjectName("CostLastOrder_ST_Entry")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.CostLastOrder_ST_Entry)
        self.PMC = QtGui.QLabel(self.PriceWidget1)
        self.PMC.setObjectName("PMC")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.PMC)
        self.PMC_Entry = QtGui.QLineEdit(self.PriceWidget1)
        self.PMC_Entry.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.PMC_Entry.setReadOnly(True)
        self.PMC_Entry.setObjectName("PMC_Entry")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.PMC_Entry)
        self.gridLayout_22.addWidget(self.PriceWidget1, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem1, 3, 0, 1, 4)
        self.PriceLine = QtGui.QFrame(self.Price_Frame)
        self.PriceLine.setFrameShape(QtGui.QFrame.HLine)
        self.PriceLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.PriceLine.setObjectName("PriceLine")
        self.gridLayout_22.addWidget(self.PriceLine, 1, 0, 1, 3)
        self.gridLayout_13.addWidget(self.Price_Frame, 1, 0, 1, 1)
        self.InputTabs.addTab(self.Price, "")
        self.Taxes = QtGui.QWidget()
        self.Taxes.setEnabled(True)
        self.Taxes.setObjectName("Taxes")
        self.gridLayout_9 = QtGui.QGridLayout(self.Taxes)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.TaxesFrame1 = QtGui.QFrame(self.Taxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaxesFrame1.sizePolicy().hasHeightForWidth())
        self.TaxesFrame1.setSizePolicy(sizePolicy)
        self.TaxesFrame1.setAutoFillBackground(True)
        self.TaxesFrame1.setObjectName("TaxesFrame1")
        self.gridLayout_7 = QtGui.QGridLayout(self.TaxesFrame1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem2, 2, 0, 1, 3)
        self.ReceitaCofins_Label = QtGui.QLabel(self.TaxesFrame1)
        self.ReceitaCofins_Label.setObjectName("ReceitaCofins_Label")
        self.gridLayout_7.addWidget(self.ReceitaCofins_Label, 11, 2, 1, 1)
        self.BaseST_Label = QtGui.QLabel(self.TaxesFrame1)
        self.BaseST_Label.setObjectName("BaseST_Label")
        self.gridLayout_7.addWidget(self.BaseST_Label, 11, 0, 1, 1)
        self.TaxesWidget1 = QtGui.QWidget(self.TaxesFrame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TaxesWidget1.sizePolicy().hasHeightForWidth())
        self.TaxesWidget1.setSizePolicy(sizePolicy)
        self.TaxesWidget1.setObjectName("TaxesWidget1")
        self.gridLayout_17 = QtGui.QGridLayout(self.TaxesWidget1)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.NCM_Entry = QtGui.QLineEdit(self.TaxesWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NCM_Entry.sizePolicy().hasHeightForWidth())
        self.NCM_Entry.setSizePolicy(sizePolicy)
        self.NCM_Entry.setObjectName("NCM_Entry")
        self.gridLayout_17.addWidget(self.NCM_Entry, 1, 1, 1, 1)
        self.NCM_Label = QtGui.QLabel(self.TaxesWidget1)
        self.NCM_Label.setObjectName("NCM_Label")
        self.gridLayout_17.addWidget(self.NCM_Label, 0, 1, 1, 1)
        self.NBS_Label = QtGui.QLabel(self.TaxesWidget1)
        self.NBS_Label.setObjectName("NBS_Label")
        self.gridLayout_17.addWidget(self.NBS_Label, 0, 0, 1, 1)
        self.NBS_Entry = QtGui.QLineEdit(self.TaxesWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NBS_Entry.sizePolicy().hasHeightForWidth())
        self.NBS_Entry.setSizePolicy(sizePolicy)
        self.NBS_Entry.setObjectName("NBS_Entry")
        self.gridLayout_17.addWidget(self.NBS_Entry, 1, 0, 1, 1)
        self.Cest_Entry = QtGui.QLineEdit(self.TaxesWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cest_Entry.sizePolicy().hasHeightForWidth())
        self.Cest_Entry.setSizePolicy(sizePolicy)
        self.Cest_Entry.setObjectName("Cest_Entry")
        self.gridLayout_17.addWidget(self.Cest_Entry, 1, 2, 1, 1)
        self.CEST_Label = QtGui.QLabel(self.TaxesWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CEST_Label.sizePolicy().hasHeightForWidth())
        self.CEST_Label.setSizePolicy(sizePolicy)
        self.CEST_Label.setMinimumSize(QtCore.QSize(62, 20))
        self.CEST_Label.setObjectName("CEST_Label")
        self.gridLayout_17.addWidget(self.CEST_Label, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.TaxesWidget1, 0, 2, 1, 1)
        self.BaseST_ComboBox = QtGui.QComboBox(self.TaxesFrame1)
        self.BaseST_ComboBox.setObjectName("BaseST_ComboBox")
        self.gridLayout_7.addWidget(self.BaseST_ComboBox, 12, 0, 1, 1)
        self.COFINS_Label = QtGui.QComboBox(self.TaxesFrame1)
        self.COFINS_Label.setObjectName("COFINS_Label")
        self.gridLayout_7.addWidget(self.COFINS_Label, 8, 2, 1, 1)
        self.Origem_Label = QtGui.QLabel(self.TaxesFrame1)
        self.Origem_Label.setObjectName("Origem_Label")
        self.gridLayout_7.addWidget(self.Origem_Label, 5, 0, 1, 1)
        self.ReceitaPIS_Entry = QtGui.QLineEdit(self.TaxesFrame1)
        self.ReceitaPIS_Entry.setObjectName("ReceitaPIS_Entry")
        self.gridLayout_7.addWidget(self.ReceitaPIS_Entry, 10, 2, 1, 1)
        self.ReceitaCofins_Entry = QtGui.QLineEdit(self.TaxesFrame1)
        self.ReceitaCofins_Entry.setObjectName("ReceitaCofins_Entry")
        self.gridLayout_7.addWidget(self.ReceitaCofins_Entry, 12, 2, 1, 1)
        self.PIS_COFINS_Line = QtGui.QFrame(self.TaxesFrame1)
        self.PIS_COFINS_Line.setFrameShape(QtGui.QFrame.HLine)
        self.PIS_COFINS_Line.setFrameShadow(QtGui.QFrame.Sunken)
        self.PIS_COFINS_Line.setObjectName("PIS_COFINS_Line")
        self.gridLayout_7.addWidget(self.PIS_COFINS_Line, 4, 2, 1, 1)
        self.PIS_ComboBox = QtGui.QComboBox(self.TaxesFrame1)
        self.PIS_ComboBox.setObjectName("PIS_ComboBox")
        self.gridLayout_7.addWidget(self.PIS_ComboBox, 6, 2, 1, 1)
        self.ICMS_ISS_Label = QtGui.QLabel(self.TaxesFrame1)
        self.ICMS_ISS_Label.setObjectName("ICMS_ISS_Label")
        self.gridLayout_7.addWidget(self.ICMS_ISS_Label, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(250, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 5, 1, 8, 1)
        self.ICMS_Label = QtGui.QLabel(self.TaxesFrame1)
        self.ICMS_Label.setObjectName("ICMS_Label")
        self.gridLayout_7.addWidget(self.ICMS_Label, 9, 0, 1, 1)
        self.PIS_COFINS_Label = QtGui.QLabel(self.TaxesFrame1)
        self.PIS_COFINS_Label.setObjectName("PIS_COFINS_Label")
        self.gridLayout_7.addWidget(self.PIS_COFINS_Label, 3, 2, 1, 1)
        self.BaseICMS_Entry = QtGui.QLineEdit(self.TaxesFrame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BaseICMS_Entry.sizePolicy().hasHeightForWidth())
        self.BaseICMS_Entry.setSizePolicy(sizePolicy)
        self.BaseICMS_Entry.setReadOnly(True)
        self.BaseICMS_Entry.setObjectName("BaseICMS_Entry")
        self.gridLayout_7.addWidget(self.BaseICMS_Entry, 14, 0, 1, 1)
        self.PIS_Label = QtGui.QLabel(self.TaxesFrame1)
        self.PIS_Label.setObjectName("PIS_Label")
        self.gridLayout_7.addWidget(self.PIS_Label, 5, 2, 1, 1)
        self.ICMS_ComboBox = QtGui.QComboBox(self.TaxesFrame1)
        self.ICMS_ComboBox.setObjectName("ICMS_ComboBox")
        self.gridLayout_7.addWidget(self.ICMS_ComboBox, 10, 0, 1, 1)
        self.COFINS_Label_2 = QtGui.QLabel(self.TaxesFrame1)
        self.COFINS_Label_2.setObjectName("COFINS_Label_2")
        self.gridLayout_7.addWidget(self.COFINS_Label_2, 7, 2, 1, 1)
        self.CSOSN_Label = QtGui.QLabel(self.TaxesFrame1)
        self.CSOSN_Label.setObjectName("CSOSN_Label")
        self.gridLayout_7.addWidget(self.CSOSN_Label, 7, 0, 1, 1)
        self.CSOSN_ComboBox = QtGui.QComboBox(self.TaxesFrame1)
        self.CSOSN_ComboBox.setObjectName("CSOSN_ComboBox")
        self.gridLayout_7.addWidget(self.CSOSN_ComboBox, 8, 0, 1, 1)
        self.ReceitaPIS_Label = QtGui.QLabel(self.TaxesFrame1)
        self.ReceitaPIS_Label.setObjectName("ReceitaPIS_Label")
        self.gridLayout_7.addWidget(self.ReceitaPIS_Label, 9, 2, 1, 1)
        self.Origem_ComboBox = QtGui.QComboBox(self.TaxesFrame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Origem_ComboBox.sizePolicy().hasHeightForWidth())
        self.Origem_ComboBox.setSizePolicy(sizePolicy)
        self.Origem_ComboBox.setObjectName("Origem_ComboBox")
        self.gridLayout_7.addWidget(self.Origem_ComboBox, 6, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 45, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem4, 19, 0, 1, 3)
        self.ICMS_Line = QtGui.QFrame(self.TaxesFrame1)
        self.ICMS_Line.setFrameShape(QtGui.QFrame.HLine)
        self.ICMS_Line.setFrameShadow(QtGui.QFrame.Sunken)
        self.ICMS_Line.setObjectName("ICMS_Line")
        self.gridLayout_7.addWidget(self.ICMS_Line, 4, 0, 1, 2)
        self.TaxesWidget2 = QtGui.QWidget(self.TaxesFrame1)
        self.TaxesWidget2.setObjectName("TaxesWidget2")
        self.gridLayout_18 = QtGui.QGridLayout(self.TaxesWidget2)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.SPED_ComboBox = QtGui.QComboBox(self.TaxesWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SPED_ComboBox.sizePolicy().hasHeightForWidth())
        self.SPED_ComboBox.setSizePolicy(sizePolicy)
        self.SPED_ComboBox.setObjectName("SPED_ComboBox")
        self.gridLayout_18.addWidget(self.SPED_ComboBox, 2, 0, 1, 1)
        self.SPED_Label = QtGui.QLabel(self.TaxesWidget2)
        self.SPED_Label.setObjectName("SPED_Label")
        self.gridLayout_18.addWidget(self.SPED_Label, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.TaxesWidget2, 0, 0, 1, 2)
        self.BaseICMS_Label = QtGui.QLabel(self.TaxesFrame1)
        self.BaseICMS_Label.setObjectName("BaseICMS_Label")
        self.gridLayout_7.addWidget(self.BaseICMS_Label, 13, 0, 1, 1)
        self.DesconsiderarEAN_ComboBox = QtGui.QComboBox(self.TaxesFrame1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesconsiderarEAN_ComboBox.sizePolicy().hasHeightForWidth())
        self.DesconsiderarEAN_ComboBox.setSizePolicy(sizePolicy)
        self.DesconsiderarEAN_ComboBox.setObjectName("DesconsiderarEAN_ComboBox")
        self.DesconsiderarEAN_ComboBox.addItem("")
        self.DesconsiderarEAN_ComboBox.addItem("")
        self.gridLayout_7.addWidget(self.DesconsiderarEAN_ComboBox, 18, 0, 1, 1)
        self.DesconsiderarEAN_Label = QtGui.QLabel(self.TaxesFrame1)
        self.DesconsiderarEAN_Label.setObjectName("DesconsiderarEAN_Label")
        self.gridLayout_7.addWidget(self.DesconsiderarEAN_Label, 17, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem5, 15, 0, 1, 1)
        self.line = QtGui.QFrame(self.TaxesFrame1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 16, 0, 1, 2)
        self.gridLayout_9.addWidget(self.TaxesFrame1, 0, 0, 1, 1)
        self.InputTabs.addTab(self.Taxes, "")
        self.SNGPC = QtGui.QWidget()
        self.SNGPC.setObjectName("SNGPC")
        self.gridLayout_12 = QtGui.QGridLayout(self.SNGPC)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.SNGPC_Frame = QtGui.QFrame(self.SNGPC)
        self.SNGPC_Frame.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SNGPC_Frame.sizePolicy().hasHeightForWidth())
        self.SNGPC_Frame.setSizePolicy(sizePolicy)
        self.SNGPC_Frame.setAutoFillBackground(True)
        self.SNGPC_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SNGPC_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.SNGPC_Frame.setObjectName("SNGPC_Frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.SNGPC_Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SNGPCWidget = QtGui.QWidget(self.SNGPC_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SNGPCWidget.sizePolicy().hasHeightForWidth())
        self.SNGPCWidget.setSizePolicy(sizePolicy)
        self.SNGPCWidget.setObjectName("SNGPCWidget")
        self.gridLayout_6 = QtGui.QGridLayout(self.SNGPCWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Antibiotico_radioButton = QtGui.QRadioButton(self.SNGPCWidget)
        self.Antibiotico_radioButton.setChecked(True)
        self.Antibiotico_radioButton.setObjectName("Antibiotico_radioButton")
        self.gridLayout_6.addWidget(self.Antibiotico_radioButton, 0, 0, 1, 1)
        self.ControleEspecial_radioButton = QtGui.QRadioButton(self.SNGPCWidget)
        self.ControleEspecial_radioButton.setObjectName("ControleEspecial_radioButton")
        self.gridLayout_6.addWidget(self.ControleEspecial_radioButton, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.SNGPCWidget, 0, 0, 1, 1)
        self.SNGPC_Frame2 = QtGui.QFrame(self.SNGPC_Frame)
        self.SNGPC_Frame2.setEnabled(False)
        self.SNGPC_Frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SNGPC_Frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.SNGPC_Frame2.setObjectName("SNGPC_Frame2")
        self.gridLayout_8 = QtGui.QGridLayout(self.SNGPC_Frame2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Volume_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.Volume_Label.setObjectName("Volume_Label")
        self.gridLayout_8.addWidget(self.Volume_Label, 3, 0, 1, 1)
        self.Volume_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.Volume_Entry.setStyleSheet("")
        self.Volume_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Volume_Entry.setReadOnly(False)
        self.Volume_Entry.setObjectName("Volume_Entry")
        self.gridLayout_8.addWidget(self.Volume_Entry, 3, 1, 1, 1)
        self.Concentracao_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.Concentracao_Entry.setStyleSheet("")
        self.Concentracao_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Concentracao_Entry.setReadOnly(False)
        self.Concentracao_Entry.setObjectName("Concentracao_Entry")
        self.gridLayout_8.addWidget(self.Concentracao_Entry, 4, 1, 1, 1)
        self.Concentracao_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.Concentracao_Label.setObjectName("Concentracao_Label")
        self.gridLayout_8.addWidget(self.Concentracao_Label, 4, 0, 1, 1)
        self.CapMedia_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.CapMedia_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CapMedia_Label.setObjectName("CapMedia_Label")
        self.gridLayout_8.addWidget(self.CapMedia_Label, 1, 0, 1, 1)
        self.DiasTrat_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.DiasTrat_Label.setObjectName("DiasTrat_Label")
        self.gridLayout_8.addWidget(self.DiasTrat_Label, 1, 2, 1, 1)
        self.CapMedia_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.CapMedia_Entry.setMouseTracking(True)
        self.CapMedia_Entry.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.CapMedia_Entry.setStyleSheet("")
        self.CapMedia_Entry.setEchoMode(QtGui.QLineEdit.Normal)
        self.CapMedia_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.CapMedia_Entry.setReadOnly(False)
        self.CapMedia_Entry.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.CapMedia_Entry.setObjectName("CapMedia_Entry")
        self.gridLayout_8.addWidget(self.CapMedia_Entry, 1, 1, 1, 1)
        self.DiasTrat_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.DiasTrat_Entry.setStyleSheet("")
        self.DiasTrat_Entry.setReadOnly(False)
        self.DiasTrat_Entry.setObjectName("DiasTrat_Entry")
        self.gridLayout_8.addWidget(self.DiasTrat_Entry, 1, 3, 1, 1)
        self.Apres_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.Apres_Entry.setStyleSheet("")
        self.Apres_Entry.setReadOnly(False)
        self.Apres_Entry.setObjectName("Apres_Entry")
        self.gridLayout_8.addWidget(self.Apres_Entry, 3, 3, 1, 1)
        self.Apres_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.Apres_Label.setObjectName("Apres_Label")
        self.gridLayout_8.addWidget(self.Apres_Label, 3, 2, 1, 1)
        self.NomeMedic_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.NomeMedic_Label.setObjectName("NomeMedic_Label")
        self.gridLayout_8.addWidget(self.NomeMedic_Label, 4, 2, 1, 1)
        self.NomeMedic_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.NomeMedic_Entry.setStyleSheet("")
        self.NomeMedic_Entry.setReadOnly(False)
        self.NomeMedic_Entry.setObjectName("NomeMedic_Entry")
        self.gridLayout_8.addWidget(self.NomeMedic_Entry, 4, 3, 1, 1)
        self.UnidEmbalagemLabel = QtGui.QLabel(self.SNGPC_Frame2)
        self.UnidEmbalagemLabel.setObjectName("UnidEmbalagemLabel")
        self.gridLayout_8.addWidget(self.UnidEmbalagemLabel, 5, 0, 1, 1)
        self.UnidEmbalagem_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.UnidEmbalagem_Entry.setStyleSheet("")
        self.UnidEmbalagem_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.UnidEmbalagem_Entry.setReadOnly(False)
        self.UnidEmbalagem_Entry.setObjectName("UnidEmbalagem_Entry")
        self.gridLayout_8.addWidget(self.UnidEmbalagem_Entry, 5, 1, 1, 1)
        self.UnidadeSNGPC_ComboBox_2 = QtGui.QComboBox(self.SNGPC_Frame2)
        self.UnidadeSNGPC_ComboBox_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnidadeSNGPC_ComboBox_2.sizePolicy().hasHeightForWidth())
        self.UnidadeSNGPC_ComboBox_2.setSizePolicy(sizePolicy)
        self.UnidadeSNGPC_ComboBox_2.setObjectName("UnidadeSNGPC_ComboBox_2")
        self.UnidadeSNGPC_ComboBox_2.addItem("")
        self.UnidadeSNGPC_ComboBox_2.addItem("")
        self.gridLayout_8.addWidget(self.UnidadeSNGPC_ComboBox_2, 5, 3, 1, 1)
        self.UnidadeSNGPC_Label_2 = QtGui.QLabel(self.SNGPC_Frame2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnidadeSNGPC_Label_2.sizePolicy().hasHeightForWidth())
        self.UnidadeSNGPC_Label_2.setSizePolicy(sizePolicy)
        self.UnidadeSNGPC_Label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.UnidadeSNGPC_Label_2.setObjectName("UnidadeSNGPC_Label_2")
        self.gridLayout_8.addWidget(self.UnidadeSNGPC_Label_2, 5, 2, 1, 1)
        self.gridLayout_2.addWidget(self.SNGPC_Frame2, 1, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 2)
        self.ControleEspecial_Frame = QtGui.QFrame(self.SNGPC_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControleEspecial_Frame.sizePolicy().hasHeightForWidth())
        self.ControleEspecial_Frame.setSizePolicy(sizePolicy)
        self.ControleEspecial_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ControleEspecial_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.ControleEspecial_Frame.setObjectName("ControleEspecial_Frame")
        self.gridLayout_16 = QtGui.QGridLayout(self.ControleEspecial_Frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ListaContEsp_Label = QtGui.QLabel(self.ControleEspecial_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaContEsp_Label.sizePolicy().hasHeightForWidth())
        self.ListaContEsp_Label.setSizePolicy(sizePolicy)
        self.ListaContEsp_Label.setVisible(False)
        self.ListaContEsp_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ListaContEsp_Label.setObjectName("ListaContEsp_Label")
        self.gridLayout_16.addWidget(self.ListaContEsp_Label, 0, 0, 1, 1)
        self.AdendoContEsp_Label = QtGui.QLabel(self.ControleEspecial_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdendoContEsp_Label.sizePolicy().hasHeightForWidth())
        self.AdendoContEsp_Label.setSizePolicy(sizePolicy)
        self.AdendoContEsp_Label.setVisible(False)
        self.AdendoContEsp_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.AdendoContEsp_Label.setObjectName("AdendoContEsp_Label")
        self.gridLayout_16.addWidget(self.AdendoContEsp_Label, 0, 1, 1, 1)
        self.ListaContEsp_ComboBox = QtGui.QComboBox(self.ControleEspecial_Frame)
        self.ListaContEsp_ComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaContEsp_ComboBox.sizePolicy().hasHeightForWidth())
        self.ListaContEsp_ComboBox.setSizePolicy(sizePolicy)
        self.ListaContEsp_ComboBox.setVisible(False)
        self.ListaContEsp_ComboBox.setObjectName("ListaContEsp_ComboBox")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.ListaContEsp_ComboBox.addItem("")
        self.gridLayout_16.addWidget(self.ListaContEsp_ComboBox, 1, 0, 1, 1)
        self.AdendoContEsp_ComboBox = QtGui.QComboBox(self.ControleEspecial_Frame)
        self.AdendoContEsp_ComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdendoContEsp_ComboBox.sizePolicy().hasHeightForWidth())
        self.AdendoContEsp_ComboBox.setSizePolicy(sizePolicy)
        self.AdendoContEsp_ComboBox.setVisible(False)
        self.AdendoContEsp_ComboBox.setObjectName("AdendoContEsp_ComboBox")
        self.AdendoContEsp_ComboBox.addItem("")
        self.gridLayout_16.addWidget(self.AdendoContEsp_ComboBox, 1, 1, 1, 1)
        self.ListaAnti_Label = QtGui.QLabel(self.ControleEspecial_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaAnti_Label.sizePolicy().hasHeightForWidth())
        self.ListaAnti_Label.setSizePolicy(sizePolicy)
        self.ListaAnti_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ListaAnti_Label.setObjectName("ListaAnti_Label")
        self.gridLayout_16.addWidget(self.ListaAnti_Label, 2, 0, 1, 1)
        self.ListaAnti_ComboBox = QtGui.QComboBox(self.ControleEspecial_Frame)
        self.ListaAnti_ComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListaAnti_ComboBox.sizePolicy().hasHeightForWidth())
        self.ListaAnti_ComboBox.setSizePolicy(sizePolicy)
        self.ListaAnti_ComboBox.setObjectName("ListaAnti_ComboBox")
        self.ListaAnti_ComboBox.addItem("")
        self.gridLayout_16.addWidget(self.ListaAnti_ComboBox, 3, 0, 1, 1)
        self.AdendoAnti_ComboBox = QtGui.QComboBox(self.ControleEspecial_Frame)
        self.AdendoAnti_ComboBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdendoAnti_ComboBox.sizePolicy().hasHeightForWidth())
        self.AdendoAnti_ComboBox.setSizePolicy(sizePolicy)
        self.AdendoAnti_ComboBox.setObjectName("AdendoAnti_ComboBox")
        self.gridLayout_16.addWidget(self.AdendoAnti_ComboBox, 3, 1, 1, 1)
        self.AdendoAnti_Label = QtGui.QLabel(self.ControleEspecial_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdendoAnti_Label.sizePolicy().hasHeightForWidth())
        self.AdendoAnti_Label.setSizePolicy(sizePolicy)
        self.AdendoAnti_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.AdendoAnti_Label.setObjectName("AdendoAnti_Label")
        self.gridLayout_16.addWidget(self.AdendoAnti_Label, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.ControleEspecial_Frame, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.SNGPC_Frame, 0, 0, 1, 1)
        self.InputTabs.addTab(self.SNGPC, "")
        self.BarCodes = QtGui.QWidget()
        self.BarCodes.setObjectName("BarCodes")
        self.gridLayout_21 = QtGui.QGridLayout(self.BarCodes)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.EAN_Frame = QtGui.QFrame(self.BarCodes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EAN_Frame.sizePolicy().hasHeightForWidth())
        self.EAN_Frame.setSizePolicy(sizePolicy)
        self.EAN_Frame.setAutoFillBackground(True)
        self.EAN_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.EAN_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.EAN_Frame.setObjectName("EAN_Frame")
        self.gridLayout_20 = QtGui.QGridLayout(self.EAN_Frame)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_8 = QtGui.QLabel(self.EAN_Frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_20.addWidget(self.label_8, 0, 1, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.EAN_Frame)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_20.addWidget(self.lineEdit_8, 0, 2, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.EAN_Frame)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_20.addWidget(self.lineEdit_10, 0, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.EAN_Frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout_20.addWidget(self.label_10, 0, 3, 1, 1)
        self.gridLayout_31 = QtGui.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.EANWidget1 = QtGui.QWidget(self.EAN_Frame)
        self.EANWidget1.setObjectName("EANWidget1")
        self.gridLayout_32 = QtGui.QGridLayout(self.EANWidget1)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.EditarButton = QtGui.QPushButton(self.EANWidget1)
        self.EditarButton.setObjectName("EditarButton")
        self.gridLayout_32.addWidget(self.EditarButton, 0, 2, 1, 1)
        self.WhatvsButton = QtGui.QPushButton(self.EANWidget1)
        self.WhatvsButton.setObjectName("WhatvsButton")
        self.gridLayout_32.addWidget(self.WhatvsButton, 1, 2, 1, 1)
        self.AdicionarButton = QtGui.QPushButton(self.EANWidget1)
        self.AdicionarButton.setObjectName("AdicionarButton")
        self.gridLayout_32.addWidget(self.AdicionarButton, 0, 1, 1, 1)
        self.ExcluirButton = QtGui.QPushButton(self.EANWidget1)
        self.ExcluirButton.setObjectName("ExcluirButton")
        self.gridLayout_32.addWidget(self.ExcluirButton, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_32.addItem(spacerItem7, 0, 0, 2, 1)
        self.gridLayout_31.addWidget(self.EANWidget1, 3, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_31.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_31.addItem(spacerItem9, 2, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem11, 1, 2, 1, 1)
        self.EANTable = QtGui.QTableWidget(self.EAN_Frame)
        self.EANTable.setObjectName("EANTable")
        self.EANTable.setColumnCount(2)
        self.EANTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.EANTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.EANTable.setHorizontalHeaderItem(1, item)
        self.EANTable.horizontalHeader().setVisible(False)
        self.EANTable.horizontalHeader().setCascadingSectionResizes(True)
        self.EANTable.horizontalHeader().setDefaultSectionSize(327)
        self.EANTable.horizontalHeader().setHighlightSections(True)
        self.EANTable.horizontalHeader().setMinimumSectionSize(80)
        self.EANTable.horizontalHeader().setStretchLastSection(False)
        self.EANTable.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_31.addWidget(self.EANTable, 1, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_31, 1, 0, 1, 6)
        spacerItem12 = QtGui.QSpacerItem(23, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem12, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(18, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem13, 0, 5, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem14, 2, 0, 1, 6)
        self.gridLayout_21.addWidget(self.EAN_Frame, 0, 0, 1, 1)
        self.InputTabs.addTab(self.BarCodes, "")
        self.verticalLayout_6.addWidget(self.InputTabs)
        self.ButtonWidget = QtGui.QWidget(self.InputFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonWidget.sizePolicy().hasHeightForWidth())
        self.ButtonWidget.setSizePolicy(sizePolicy)
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.gridLayout_15 = QtGui.QGridLayout(self.ButtonWidget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Submit_Button = QtGui.QPushButton(self.ButtonWidget)
        self.Submit_Button.setObjectName("Submit_Button")
        self.gridLayout_15.addWidget(self.Submit_Button, 0, 0, 1, 1)
        self.Clear_Button = QtGui.QPushButton(self.ButtonWidget)
        self.Clear_Button.setObjectName("Clear_Button")
        self.gridLayout_15.addWidget(self.Clear_Button, 0, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.ButtonWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_15.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.Back_Button = QtGui.QPushButton(self.ButtonWidget)
        self.Back_Button.setObjectName("Back_Button")
        self.gridLayout_15.addWidget(self.Back_Button, 0, 2, 1, 1)
        self.Search_Button = QtGui.QPushButton(self.ButtonWidget)
        self.Search_Button.setObjectName("Search_Button")
        self.gridLayout_15.addWidget(self.Search_Button, 0, 3, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.ButtonWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_15.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.ButtonWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_15.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.ButtonWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_15.addWidget(self.pushButton_8, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.ButtonWidget)
        self.gridLayout_14.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.InputFrame, 0, 0, 1, 1)

        self.retranslateUi(InputPage)
        self.InputTabs.setCurrentIndex(2)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.SNGPC_Frame.setEnabled)
        QtCore.QObject.connect(self.MedCheckBox_2, QtCore.SIGNAL("toggled(bool)"), self.PrintAtiv_Entry.setEnabled)
        QtCore.QObject.connect(self.MedCheckBox_2, QtCore.SIGNAL("toggled(bool)"), self.Reg_Entry.setEnabled)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaContEsp_Label.setHidden)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaContEsp_ComboBox.setHidden)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoContEsp_Label.setHidden)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoContEsp_ComboBox.setHidden)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaContEsp_Label.setVisible)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaContEsp_ComboBox.setVisible)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoContEsp_Label.setVisible)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoContEsp_ComboBox.setVisible)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaAnti_Label.setHidden)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoAnti_Label.setHidden)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaAnti_ComboBox.setHidden)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoAnti_ComboBox.setHidden)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaAnti_Label.setVisible)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoAnti_Label.setVisible)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.ListaAnti_ComboBox.setVisible)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.AdendoAnti_ComboBox.setVisible)
        QtCore.QObject.connect(self.MedCheckBox_2, QtCore.SIGNAL("toggled(bool)"), self.Lab_Entry.setEnabled)
        QtCore.QObject.connect(self.MedCheckBox_2, QtCore.SIGNAL("toggled(bool)"), self.Lab_Label.setEnabled)
        QtCore.QObject.connect(self.MedCheckBox_2, QtCore.SIGNAL("toggled(bool)"), self.Fabr_Label.setDisabled)
        QtCore.QObject.connect(self.MedCheckBox_2, QtCore.SIGNAL("toggled(bool)"), self.Fabr_Entry.setDisabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.SNGPC_Frame2.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.ControleEspecial_Frame.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.UnidadeSNGPC_ComboBox_2.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.ListaAnti_ComboBox.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.ListaContEsp_ComboBox.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.AdendoAnti_ComboBox.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.AdendoContEsp_ComboBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(InputPage)

    def retranslateUi(self, InputPage):
        InputPage.setWindowTitle(QtGui.QApplication.translate("InputPage", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.MedCheckBox_2.setText(QtGui.QApplication.translate("InputPage", "Medicamento", None, QtGui.QApplication.UnicodeUTF8))
        self.SNGPC_Checkbox.setText(QtGui.QApplication.translate("InputPage", "SNGPC", None, QtGui.QApplication.UnicodeUTF8))
        self.Type_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "Genérico", None, QtGui.QApplication.UnicodeUTF8))
        self.Type_ComboBox.setItemText(1, QtGui.QApplication.translate("InputPage", "Similar", None, QtGui.QApplication.UnicodeUTF8))
        self.Type_ComboBox.setItemText(2, QtGui.QApplication.translate("InputPage", "Referência", None, QtGui.QApplication.UnicodeUTF8))
        self.PrinAtiv_Label.setText(QtGui.QApplication.translate("InputPage", "Princípio Ativo", None, QtGui.QApplication.UnicodeUTF8))
        self.PrinAtivSearchButton.setToolTip(QtGui.QApplication.translate("InputPage", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Product_Label_2.setText(QtGui.QApplication.translate("InputPage", "Produto", None, QtGui.QApplication.UnicodeUTF8))
        self.Reg_Label_2.setText(QtGui.QApplication.translate("InputPage", "Reg. Ministério da Saúde", None, QtGui.QApplication.UnicodeUTF8))
        self.Descr_Label.setText(QtGui.QApplication.translate("InputPage", "Descrição Completa", None, QtGui.QApplication.UnicodeUTF8))
        self.Lab_Label.setText(QtGui.QApplication.translate("InputPage", "Laboratório", None, QtGui.QApplication.UnicodeUTF8))
        self.Fabr_Label.setText(QtGui.QApplication.translate("InputPage", "Fabricante", None, QtGui.QApplication.UnicodeUTF8))
        self.LabSearchButton.setToolTip(QtGui.QApplication.translate("InputPage", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.FabrSearchButton.setToolTip(QtGui.QApplication.translate("InputPage", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab2Search.setToolTip(QtGui.QApplication.translate("InputPage", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab3Search.setToolTip(QtGui.QApplication.translate("InputPage", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TabAux1_Label.setText(QtGui.QApplication.translate("InputPage", "Tabela Aux1", None, QtGui.QApplication.UnicodeUTF8))
        self.Etiqueta_Label.setText(QtGui.QApplication.translate("InputPage", "Etiqueta Gôndula", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab1Search.setToolTip(QtGui.QApplication.translate("InputPage", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TabAux2_Label.setText(QtGui.QApplication.translate("InputPage", "Tabela Aux2", None, QtGui.QApplication.UnicodeUTF8))
        self.TabAux3_Label.setText(QtGui.QApplication.translate("InputPage", "Tabela Aux3", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.Descricao), QtGui.QApplication.translate("InputPage", "Descrição", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_Label.setText(QtGui.QApplication.translate("InputPage", "Tipo de Preço de Custo Atualizado na Entr. Mercadoria", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "VLR. UNITÁRIO BRUTO", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(1, QtGui.QApplication.translate("InputPage", "VLR. UNITÁRIO BRUTO + ST", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(2, QtGui.QApplication.translate("InputPage", "VLR. UNITÁRIO BRUTO + ST + IPI", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(3, QtGui.QApplication.translate("InputPage", "VLR. UNITÁRIO LÍQUIDO", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(4, QtGui.QApplication.translate("InputPage", "VLR. UNITÁRIO LÍQUIDO + ST", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(5, QtGui.QApplication.translate("InputPage", "VLR. UNITÁRIO LÍQUIDO + ST + IPI", None, QtGui.QApplication.UnicodeUTF8))
        self.Discount_Label.setText(QtGui.QApplication.translate("InputPage", "Desconto(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.MaxDiscount_Label.setText(QtGui.QApplication.translate("InputPage", "Desconto Max(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.SellPrice_Label.setText(QtGui.QApplication.translate("InputPage", "Preço de Venda", None, QtGui.QApplication.UnicodeUTF8))
        self.CostPrice_Label.setText(QtGui.QApplication.translate("InputPage", "Preço de Custo", None, QtGui.QApplication.UnicodeUTF8))
        self.ProfitMargin_Label.setText(QtGui.QApplication.translate("InputPage", "Margem de Lucro(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.AllowDiscount_Label.setText(QtGui.QApplication.translate("InputPage", "Permite Desconto na Venda?", None, QtGui.QApplication.UnicodeUTF8))
        self.AllowDiscount_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "SIM", None, QtGui.QApplication.UnicodeUTF8))
        self.AllowDiscount_ComboBox.setItemText(1, QtGui.QApplication.translate("InputPage", "NÃO", None, QtGui.QApplication.UnicodeUTF8))
        self.CostLastOrder.setText(QtGui.QApplication.translate("InputPage", "Custo Última Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.CostLastOrder_ST.setText(QtGui.QApplication.translate("InputPage", "Última Entrada + ST", None, QtGui.QApplication.UnicodeUTF8))
        self.PMC.setText(QtGui.QApplication.translate("InputPage", "Valor PMC", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.Price), QtGui.QApplication.translate("InputPage", "Preço", None, QtGui.QApplication.UnicodeUTF8))
        self.ReceitaCofins_Label.setText(QtGui.QApplication.translate("InputPage", "Natur. Receita COFINS", None, QtGui.QApplication.UnicodeUTF8))
        self.BaseST_Label.setText(QtGui.QApplication.translate("InputPage", "Tipo Base ST", None, QtGui.QApplication.UnicodeUTF8))
        self.NCM_Label.setText(QtGui.QApplication.translate("InputPage", "Classif. Fiscal/NCM", None, QtGui.QApplication.UnicodeUTF8))
        self.NBS_Label.setText(QtGui.QApplication.translate("InputPage", "Código NBS", None, QtGui.QApplication.UnicodeUTF8))
        self.CEST_Label.setText(QtGui.QApplication.translate("InputPage", "Classif. CEST", None, QtGui.QApplication.UnicodeUTF8))
        self.Origem_Label.setText(QtGui.QApplication.translate("InputPage", "Origem", None, QtGui.QApplication.UnicodeUTF8))
        self.ICMS_ISS_Label.setText(QtGui.QApplication.translate("InputPage", "ICMS/ISS", None, QtGui.QApplication.UnicodeUTF8))
        self.ICMS_Label.setText(QtGui.QApplication.translate("InputPage", "Alíq. ICMS/ISS", None, QtGui.QApplication.UnicodeUTF8))
        self.PIS_COFINS_Label.setText(QtGui.QApplication.translate("InputPage", "PIS/COFINS", None, QtGui.QApplication.UnicodeUTF8))
        self.PIS_Label.setText(QtGui.QApplication.translate("InputPage", "CST PIS", None, QtGui.QApplication.UnicodeUTF8))
        self.COFINS_Label_2.setText(QtGui.QApplication.translate("InputPage", "CST COFINS", None, QtGui.QApplication.UnicodeUTF8))
        self.CSOSN_Label.setText(QtGui.QApplication.translate("InputPage", "CSOSN/CST ICMS", None, QtGui.QApplication.UnicodeUTF8))
        self.ReceitaPIS_Label.setText(QtGui.QApplication.translate("InputPage", "Natur. Receita PIS", None, QtGui.QApplication.UnicodeUTF8))
        self.SPED_Label.setText(QtGui.QApplication.translate("InputPage", "Tipo SPED", None, QtGui.QApplication.UnicodeUTF8))
        self.BaseICMS_Label.setText(QtGui.QApplication.translate("InputPage", "Red. Base ICMS (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.DesconsiderarEAN_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "SIM", None, QtGui.QApplication.UnicodeUTF8))
        self.DesconsiderarEAN_ComboBox.setItemText(1, QtGui.QApplication.translate("InputPage", "NÃO", None, QtGui.QApplication.UnicodeUTF8))
        self.DesconsiderarEAN_Label.setText(QtGui.QApplication.translate("InputPage", "Desconsiderar Cód. Barras na Geração NFC-e/NF-e/CF-e:", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.Taxes), QtGui.QApplication.translate("InputPage", "Tributação", None, QtGui.QApplication.UnicodeUTF8))
        self.Antibiotico_radioButton.setText(QtGui.QApplication.translate("InputPage", "Antibióticos", None, QtGui.QApplication.UnicodeUTF8))
        self.ControleEspecial_radioButton.setText(QtGui.QApplication.translate("InputPage", "Controle Especial", None, QtGui.QApplication.UnicodeUTF8))
        self.Volume_Label.setText(QtGui.QApplication.translate("InputPage", "Volume(ML)", None, QtGui.QApplication.UnicodeUTF8))
        self.Concentracao_Label.setText(QtGui.QApplication.translate("InputPage", "Concentração(MG)", None, QtGui.QApplication.UnicodeUTF8))
        self.CapMedia_Label.setText(QtGui.QApplication.translate("InputPage", "Cap. Média (ML)", None, QtGui.QApplication.UnicodeUTF8))
        self.DiasTrat_Label.setText(QtGui.QApplication.translate("InputPage", "Dias Tratamento", None, QtGui.QApplication.UnicodeUTF8))
        self.Apres_Label.setText(QtGui.QApplication.translate("InputPage", "Apres./Concentr.", None, QtGui.QApplication.UnicodeUTF8))
        self.NomeMedic_Label.setText(QtGui.QApplication.translate("InputPage", "Nome Medicamento", None, QtGui.QApplication.UnicodeUTF8))
        self.UnidEmbalagemLabel.setText(QtGui.QApplication.translate("InputPage", "Unid. por Embalagem", None, QtGui.QApplication.UnicodeUTF8))
        self.UnidadeSNGPC_ComboBox_2.setItemText(0, QtGui.QApplication.translate("InputPage", "Caixa", None, QtGui.QApplication.UnicodeUTF8))
        self.UnidadeSNGPC_ComboBox_2.setItemText(1, QtGui.QApplication.translate("InputPage", "Frasco", None, QtGui.QApplication.UnicodeUTF8))
        self.UnidadeSNGPC_Label_2.setText(QtGui.QApplication.translate("InputPage", "Unidade SNGPC", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_Label.setText(QtGui.QApplication.translate("InputPage", "Lista", None, QtGui.QApplication.UnicodeUTF8))
        self.AdendoContEsp_Label.setText(QtGui.QApplication.translate("InputPage", "Adendo", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "A1", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(1, QtGui.QApplication.translate("InputPage", "A2", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(2, QtGui.QApplication.translate("InputPage", "A3", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(3, QtGui.QApplication.translate("InputPage", "B1", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(4, QtGui.QApplication.translate("InputPage", "B2", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(5, QtGui.QApplication.translate("InputPage", "C1", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(6, QtGui.QApplication.translate("InputPage", "C2", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(7, QtGui.QApplication.translate("InputPage", "C3", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(8, QtGui.QApplication.translate("InputPage", "C4", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaContEsp_ComboBox.setItemText(9, QtGui.QApplication.translate("InputPage", "C5", None, QtGui.QApplication.UnicodeUTF8))
        self.AdendoContEsp_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "Adendo Teste", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaAnti_Label.setText(QtGui.QApplication.translate("InputPage", "Lista", None, QtGui.QApplication.UnicodeUTF8))
        self.ListaAnti_ComboBox.setItemText(0, QtGui.QApplication.translate("InputPage", "N1", None, QtGui.QApplication.UnicodeUTF8))
        self.AdendoAnti_Label.setText(QtGui.QApplication.translate("InputPage", "Adendo", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.SNGPC), QtGui.QApplication.translate("InputPage", "SNGPC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("InputPage", "Cod. Barras Adicional", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("InputPage", "Fator", None, QtGui.QApplication.UnicodeUTF8))
        self.EditarButton.setText(QtGui.QApplication.translate("InputPage", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.WhatvsButton.setText(QtGui.QApplication.translate("InputPage", "Whatvs", None, QtGui.QApplication.UnicodeUTF8))
        self.AdicionarButton.setText(QtGui.QApplication.translate("InputPage", "Adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.ExcluirButton.setText(QtGui.QApplication.translate("InputPage", "Excluir", None, QtGui.QApplication.UnicodeUTF8))
        self.EANTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("InputPage", "EAN", None, QtGui.QApplication.UnicodeUTF8))
        self.EANTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("InputPage", "Fator", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.BarCodes), QtGui.QApplication.translate("InputPage", "Código de Barras", None, QtGui.QApplication.UnicodeUTF8))
        self.Submit_Button.setText(QtGui.QApplication.translate("InputPage", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.Clear_Button.setText(QtGui.QApplication.translate("InputPage", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("InputPage", "Whatvs3", None, QtGui.QApplication.UnicodeUTF8))
        self.Back_Button.setText(QtGui.QApplication.translate("InputPage", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.Search_Button.setText(QtGui.QApplication.translate("InputPage", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("InputPage", "Whatvs1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("InputPage", "Whatvs2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("InputPage", "Whatvs4", None, QtGui.QApplication.UnicodeUTF8))

import npx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    InputPage = QtGui.QFrame()
    ui = Ui_InputPage()
    ui.setupUi(InputPage)
    InputPage.show()
    sys.exit(app.exec_())

