# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guilh\Desktop\NewPharmaExperience\npx_mock\src\GUI\InputProdPage.ui'
#
# Created: Thu Mar 22 21:32:23 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScrollArea(object):
    def setupUi(self, ScrollArea):
        ScrollArea.setObjectName("ScrollArea")
        ScrollArea.resize(1621, 879)
        ScrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -75, 1602, 952))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.InputFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.InputFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.InputFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.InputFrame.setObjectName("InputFrame")
        self.gridLayout = QtGui.QGridLayout(self.InputFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtGui.QWidget(self.InputFrame)
        self.widget.setObjectName("widget")
        self.gridLayout_15 = QtGui.QGridLayout(self.widget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Submit_Button = QtGui.QPushButton(self.widget)
        self.Submit_Button.setObjectName("Submit_Button")
        self.gridLayout_15.addWidget(self.Submit_Button, 0, 1, 1, 1)
        self.Clear_Button = QtGui.QPushButton(self.widget)
        self.Clear_Button.setObjectName("Clear_Button")
        self.gridLayout_15.addWidget(self.Clear_Button, 0, 2, 1, 1)
        self.Back_Button = QtGui.QPushButton(self.widget)
        self.Back_Button.setObjectName("Back_Button")
        self.gridLayout_15.addWidget(self.Back_Button, 0, 3, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_15.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.Search_Button = QtGui.QPushButton(self.widget)
        self.Search_Button.setObjectName("Search_Button")
        self.gridLayout_15.addWidget(self.Search_Button, 0, 4, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_15.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_15.addWidget(self.pushButton_7, 1, 3, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_15.addWidget(self.pushButton_8, 1, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout_InputFrame = QtGui.QVBoxLayout()
        self.verticalLayout_InputFrame.setObjectName("verticalLayout_InputFrame")
        self.horizontalLayout_InputFrame = QtGui.QHBoxLayout()
        self.horizontalLayout_InputFrame.setObjectName("horizontalLayout_InputFrame")
        self.verticalLayout2_InputFrame = QtGui.QVBoxLayout()
        self.verticalLayout2_InputFrame.setObjectName("verticalLayout2_InputFrame")
        self.Product_Label_2 = QtGui.QLabel(self.InputFrame)
        self.Product_Label_2.setObjectName("Product_Label_2")
        self.verticalLayout2_InputFrame.addWidget(self.Product_Label_2)
        self.Product_Entry_2 = QtGui.QLineEdit(self.InputFrame)
        self.Product_Entry_2.setObjectName("Product_Entry_2")
        self.verticalLayout2_InputFrame.addWidget(self.Product_Entry_2)
        self.horizontalLayout_InputFrame.addLayout(self.verticalLayout2_InputFrame)
        self.MedCheckBox_2 = QtGui.QCheckBox(self.InputFrame)
        self.MedCheckBox_2.setChecked(True)
        self.MedCheckBox_2.setObjectName("MedCheckBox_2")
        self.horizontalLayout_InputFrame.addWidget(self.MedCheckBox_2)
        self.verticalLayout_InputFrame.addLayout(self.horizontalLayout_InputFrame)
        self.InputTabs = QtGui.QTabWidget(self.InputFrame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.InputTabs.setPalette(palette)
        self.InputTabs.setAutoFillBackground(True)
        self.InputTabs.setStyleSheet("")
        self.InputTabs.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.InputTabs.setObjectName("InputTabs")
        self.Descricao = QtGui.QWidget()
        self.Descricao.setObjectName("Descricao")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.Descricao)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Description_Frame = QtGui.QFrame(self.Descricao)
        self.Description_Frame.setAutoFillBackground(True)
        self.Description_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Description_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Description_Frame.setObjectName("Description_Frame")
        self.gridLayout_11 = QtGui.QGridLayout(self.Description_Frame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Descr_Widget2 = QtGui.QWidget(self.Description_Frame)
        self.Descr_Widget2.setObjectName("Descr_Widget2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Descr_Widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SNGPC_Checkbox = QtGui.QCheckBox(self.Descr_Widget2)
        self.SNGPC_Checkbox.setAutoRepeat(False)
        self.SNGPC_Checkbox.setTristate(False)
        self.SNGPC_Checkbox.setObjectName("SNGPC_Checkbox")
        self.verticalLayout_3.addWidget(self.SNGPC_Checkbox)
        self.Type_ComboBox = QtGui.QComboBox(self.Descr_Widget2)
        self.Type_ComboBox.setObjectName("Type_ComboBox")
        self.Type_ComboBox.addItem("")
        self.Type_ComboBox.addItem("")
        self.Type_ComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.Type_ComboBox)
        self.gridLayout_11.addWidget(self.Descr_Widget2, 0, 1, 1, 1)
        self.Descr_Widget1 = QtGui.QWidget(self.Description_Frame)
        self.Descr_Widget1.setObjectName("Descr_Widget1")
        self.gridLayout_3 = QtGui.QGridLayout(self.Descr_Widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Lab_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.Lab_Entry.setObjectName("Lab_Entry")
        self.gridLayout_3.addWidget(self.Lab_Entry, 1, 1, 1, 1)
        self.PrinAtiv_Label = QtGui.QLabel(self.Descr_Widget1)
        self.PrinAtiv_Label.setObjectName("PrinAtiv_Label")
        self.gridLayout_3.addWidget(self.PrinAtiv_Label, 2, 0, 1, 1)
        self.PrintAtiv_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.PrintAtiv_Entry.setObjectName("PrintAtiv_Entry")
        self.gridLayout_3.addWidget(self.PrintAtiv_Entry, 2, 1, 1, 1)
        self.Descr_Label = QtGui.QLabel(self.Descr_Widget1)
        self.Descr_Label.setObjectName("Descr_Label")
        self.gridLayout_3.addWidget(self.Descr_Label, 0, 0, 1, 1)
        self.Desc_Entry = QtGui.QLineEdit(self.Descr_Widget1)
        self.Desc_Entry.setObjectName("Desc_Entry")
        self.gridLayout_3.addWidget(self.Desc_Entry, 0, 1, 1, 1)
        self.Lab_Label = QtGui.QLabel(self.Descr_Widget1)
        self.Lab_Label.setObjectName("Lab_Label")
        self.gridLayout_3.addWidget(self.Lab_Label, 1, 0, 1, 1)
        self.LabSearchButton = QtGui.QPushButton(self.Descr_Widget1)
        self.LabSearchButton.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.LabSearchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/NPX ICO/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LabSearchButton.setIcon(icon)
        self.LabSearchButton.setObjectName("LabSearchButton")
        self.gridLayout_3.addWidget(self.LabSearchButton, 1, 2, 1, 1)
        self.PrinAtivSearchButton = QtGui.QPushButton(self.Descr_Widget1)
        self.PrinAtivSearchButton.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.PrinAtivSearchButton.setText("")
        self.PrinAtivSearchButton.setIcon(icon)
        self.PrinAtivSearchButton.setObjectName("PrinAtivSearchButton")
        self.gridLayout_3.addWidget(self.PrinAtivSearchButton, 2, 2, 1, 1)
        self.gridLayout_11.addWidget(self.Descr_Widget1, 0, 0, 1, 1)
        self.Descr_Widget3 = QtGui.QWidget(self.Description_Frame)
        self.Descr_Widget3.setObjectName("Descr_Widget3")
        self.gridLayout_10 = QtGui.QGridLayout(self.Descr_Widget3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Tab3Search = QtGui.QPushButton(self.Descr_Widget3)
        self.Tab3Search.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.Tab3Search.setText("")
        self.Tab3Search.setIcon(icon)
        self.Tab3Search.setObjectName("Tab3Search")
        self.gridLayout_10.addWidget(self.Tab3Search, 3, 3, 1, 1)
        self.Tab2Search = QtGui.QPushButton(self.Descr_Widget3)
        self.Tab2Search.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.Tab2Search.setText("")
        self.Tab2Search.setIcon(icon)
        self.Tab2Search.setObjectName("Tab2Search")
        self.gridLayout_10.addWidget(self.Tab2Search, 2, 3, 1, 1)
        self.Tab1Search = QtGui.QPushButton(self.Descr_Widget3)
        self.Tab1Search.setStyleSheet("image: url(:/NPX ICO/search.png);")
        self.Tab1Search.setText("")
        self.Tab1Search.setIcon(icon)
        self.Tab1Search.setObjectName("Tab1Search")
        self.gridLayout_10.addWidget(self.Tab1Search, 1, 3, 1, 1)
        self.TabAux1_Label = QtGui.QLabel(self.Descr_Widget3)
        self.TabAux1_Label.setObjectName("TabAux1_Label")
        self.gridLayout_10.addWidget(self.TabAux1_Label, 1, 1, 1, 1)
        self.TabAux2_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.TabAux2_Entry.setObjectName("TabAux2_Entry")
        self.gridLayout_10.addWidget(self.TabAux2_Entry, 2, 2, 1, 1)
        self.Etiqueta_Label = QtGui.QLabel(self.Descr_Widget3)
        self.Etiqueta_Label.setObjectName("Etiqueta_Label")
        self.gridLayout_10.addWidget(self.Etiqueta_Label, 0, 1, 1, 1)
        self.TabAux3_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.TabAux3_Entry.setObjectName("TabAux3_Entry")
        self.gridLayout_10.addWidget(self.TabAux3_Entry, 3, 2, 1, 1)
        self.TabAux2_Label = QtGui.QLabel(self.Descr_Widget3)
        self.TabAux2_Label.setObjectName("TabAux2_Label")
        self.gridLayout_10.addWidget(self.TabAux2_Label, 2, 1, 1, 1)
        self.Etiqueta_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.Etiqueta_Entry.setObjectName("Etiqueta_Entry")
        self.gridLayout_10.addWidget(self.Etiqueta_Entry, 0, 2, 1, 1)
        self.TabAux1_Entry = QtGui.QLineEdit(self.Descr_Widget3)
        self.TabAux1_Entry.setObjectName("TabAux1_Entry")
        self.gridLayout_10.addWidget(self.TabAux1_Entry, 1, 2, 1, 1)
        self.TabAux3_Label = QtGui.QLabel(self.Descr_Widget3)
        self.TabAux3_Label.setObjectName("TabAux3_Label")
        self.gridLayout_10.addWidget(self.TabAux3_Label, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 0, 0, 4, 1)
        spacerItem4 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 4, 4, 1)
        self.gridLayout_11.addWidget(self.Descr_Widget3, 1, 0, 1, 2)
        self.verticalLayout_15.addWidget(self.Description_Frame)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.InputTabs.addTab(self.Descricao, "")
        self.Price = QtGui.QWidget()
        self.Price.setObjectName("Price")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.Price)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Price_Frame = QtGui.QFrame(self.Price)
        self.Price_Frame.setAutoFillBackground(True)
        self.Price_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Price_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Price_Frame.setObjectName("Price_Frame")
        self.PriceLine1 = QtGui.QFrame(self.Price_Frame)
        self.PriceLine1.setGeometry(QtCore.QRect(10, 93, 1062, 16))
        self.PriceLine1.setFrameShape(QtGui.QFrame.HLine)
        self.PriceLine1.setFrameShadow(QtGui.QFrame.Sunken)
        self.PriceLine1.setObjectName("PriceLine1")
        self.frame = QtGui.QFrame(self.Price_Frame)
        self.frame.setGeometry(QtCore.QRect(10, 102, 438, 123))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PriceWidget3 = QtGui.QWidget(self.frame)
        self.PriceWidget3.setObjectName("PriceWidget3")
        self.formLayout_4 = QtGui.QFormLayout(self.PriceWidget3)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.CostLastOrder = QtGui.QLabel(self.PriceWidget3)
        self.CostLastOrder.setObjectName("CostLastOrder")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.CostLastOrder)
        self.CostLastOrder_Entry = QtGui.QLineEdit(self.PriceWidget3)
        self.CostLastOrder_Entry.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.CostLastOrder_Entry.setReadOnly(True)
        self.CostLastOrder_Entry.setObjectName("CostLastOrder_Entry")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.CostLastOrder_Entry)
        self.CostLastOrder_ST = QtGui.QLabel(self.PriceWidget3)
        self.CostLastOrder_ST.setObjectName("CostLastOrder_ST")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.CostLastOrder_ST)
        self.CostLastOrder_ST_Entry = QtGui.QLineEdit(self.PriceWidget3)
        self.CostLastOrder_ST_Entry.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.CostLastOrder_ST_Entry.setReadOnly(True)
        self.CostLastOrder_ST_Entry.setObjectName("CostLastOrder_ST_Entry")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.CostLastOrder_ST_Entry)
        self.PMC = QtGui.QLabel(self.PriceWidget3)
        self.PMC.setObjectName("PMC")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.PMC)
        self.PMC_Entry = QtGui.QLineEdit(self.PriceWidget3)
        self.PMC_Entry.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.PMC_Entry.setReadOnly(True)
        self.PMC_Entry.setObjectName("PMC_Entry")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.PMC_Entry)
        self.horizontalLayout_6.addWidget(self.PriceWidget3)
        self.PriceWidget5 = QtGui.QWidget(self.frame)
        self.PriceWidget5.setObjectName("PriceWidget5")
        self.gridLayout_5 = QtGui.QGridLayout(self.PriceWidget5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.AllowDiscount_ComboBox = QtGui.QComboBox(self.PriceWidget5)
        self.AllowDiscount_ComboBox.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.AllowDiscount_ComboBox.setObjectName("AllowDiscount_ComboBox")
        self.AllowDiscount_ComboBox.addItem("")
        self.AllowDiscount_ComboBox.addItem("")
        self.gridLayout_5.addWidget(self.AllowDiscount_ComboBox, 1, 0, 1, 1)
        self.AllowDiscount_Label = QtGui.QLabel(self.PriceWidget5)
        self.AllowDiscount_Label.setObjectName("AllowDiscount_Label")
        self.gridLayout_5.addWidget(self.AllowDiscount_Label, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 2, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.PriceWidget5)
        self.PriceLine2 = QtGui.QFrame(self.Price_Frame)
        self.PriceLine2.setGeometry(QtCore.QRect(10, 230, 1062, 16))
        self.PriceLine2.setFrameShape(QtGui.QFrame.HLine)
        self.PriceLine2.setFrameShadow(QtGui.QFrame.Sunken)
        self.PriceLine2.setObjectName("PriceLine2")
        self.frame_3 = QtGui.QFrame(self.Price_Frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 240, 1062, 58))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.PriceWidget1 = QtGui.QWidget(self.frame_3)
        self.PriceWidget1.setObjectName("PriceWidget1")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.PriceWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CostPrice_Label = QtGui.QLabel(self.PriceWidget1)
        self.CostPrice_Label.setObjectName("CostPrice_Label")
        self.horizontalLayout_2.addWidget(self.CostPrice_Label)
        self.CostPrice_Entry = QtGui.QLineEdit(self.PriceWidget1)
        self.CostPrice_Entry.setObjectName("CostPrice_Entry")
        self.horizontalLayout_2.addWidget(self.CostPrice_Entry)
        self.ProfitMargin_Label = QtGui.QLabel(self.PriceWidget1)
        self.ProfitMargin_Label.setObjectName("ProfitMargin_Label")
        self.horizontalLayout_2.addWidget(self.ProfitMargin_Label)
        self.ProfitMargin_Entry = QtGui.QLineEdit(self.PriceWidget1)
        self.ProfitMargin_Entry.setObjectName("ProfitMargin_Entry")
        self.horizontalLayout_2.addWidget(self.ProfitMargin_Entry)
        self.SellPrice_Label = QtGui.QLabel(self.PriceWidget1)
        self.SellPrice_Label.setObjectName("SellPrice_Label")
        self.horizontalLayout_2.addWidget(self.SellPrice_Label)
        self.SellPrice_Entry = QtGui.QLineEdit(self.PriceWidget1)
        self.SellPrice_Entry.setObjectName("SellPrice_Entry")
        self.horizontalLayout_2.addWidget(self.SellPrice_Entry)
        self.horizontalLayout_7.addWidget(self.PriceWidget1)
        self.PriceWidget2 = QtGui.QWidget(self.frame_3)
        self.PriceWidget2.setObjectName("PriceWidget2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.PriceWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Discount_Label = QtGui.QLabel(self.PriceWidget2)
        self.Discount_Label.setObjectName("Discount_Label")
        self.horizontalLayout_3.addWidget(self.Discount_Label)
        self.Discount_Entry = QtGui.QLineEdit(self.PriceWidget2)
        self.Discount_Entry.setObjectName("Discount_Entry")
        self.horizontalLayout_3.addWidget(self.Discount_Entry)
        self.MaxDiscount_Label = QtGui.QLabel(self.PriceWidget2)
        self.MaxDiscount_Label.setObjectName("MaxDiscount_Label")
        self.horizontalLayout_3.addWidget(self.MaxDiscount_Label)
        self.MaxDiscount_Entry = QtGui.QLineEdit(self.PriceWidget2)
        self.MaxDiscount_Entry.setObjectName("MaxDiscount_Entry")
        self.horizontalLayout_3.addWidget(self.MaxDiscount_Entry)
        self.horizontalLayout_7.addWidget(self.PriceWidget2)
        self.frame_4 = QtGui.QFrame(self.Price_Frame)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 491, 77))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PriceWidget4 = QtGui.QWidget(self.frame_4)
        self.PriceWidget4.setObjectName("PriceWidget4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.PriceWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PriceCostType_Label = QtGui.QLabel(self.PriceWidget4)
        self.PriceCostType_Label.setObjectName("PriceCostType_Label")
        self.verticalLayout_2.addWidget(self.PriceCostType_Label)
        self.PriceCostType_ComboBox = QtGui.QComboBox(self.PriceWidget4)
        self.PriceCostType_ComboBox.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.PriceCostType_ComboBox.setObjectName("PriceCostType_ComboBox")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.PriceCostType_ComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.PriceCostType_ComboBox)
        self.horizontalLayout_8.addWidget(self.PriceWidget4)
        self.PriceWidget6 = QtGui.QWidget(self.frame_4)
        self.PriceWidget6.setObjectName("PriceWidget6")
        self.gridLayout_6 = QtGui.QGridLayout(self.PriceWidget6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.LastPriceDate = QtGui.QDateEdit(self.PriceWidget6)
        self.LastPriceDate.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.LastPriceDate.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.LastPriceDate.setReadOnly(True)
        self.LastPriceDate.setDate(QtCore.QDate(2000, 1, 7))
        self.LastPriceDate.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.LastPriceDate.setCalendarPopup(True)
        self.LastPriceDate.setObjectName("LastPriceDate")
        self.gridLayout_6.addWidget(self.LastPriceDate, 1, 0, 1, 1)
        self.LastPriceDate_Label = QtGui.QLabel(self.PriceWidget6)
        self.LastPriceDate_Label.setObjectName("LastPriceDate_Label")
        self.gridLayout_6.addWidget(self.LastPriceDate_Label, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 0, 1, 2, 1)
        self.horizontalLayout_8.addWidget(self.PriceWidget6)
        self.verticalLayout_12.addWidget(self.Price_Frame)
        self.InputTabs.addTab(self.Price, "")
        self.Taxes = QtGui.QWidget()
        self.Taxes.setObjectName("Taxes")
        self.gridLayout_13 = QtGui.QGridLayout(self.Taxes)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.TaxesWidget1 = QtGui.QWidget(self.Taxes)
        self.TaxesWidget1.setAutoFillBackground(True)
        self.TaxesWidget1.setObjectName("TaxesWidget1")
        self.gridLayout_9 = QtGui.QGridLayout(self.TaxesWidget1)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.splitter_7 = QtGui.QSplitter(self.TaxesWidget1)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.layoutWidget_5 = QtGui.QWidget(self.splitter_7)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.SPED_Label = QtGui.QLabel(self.layoutWidget_5)
        self.SPED_Label.setObjectName("SPED_Label")
        self.verticalLayout_23.addWidget(self.SPED_Label)
        self.SPED_ComboBox = QtGui.QComboBox(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SPED_ComboBox.sizePolicy().hasHeightForWidth())
        self.SPED_ComboBox.setSizePolicy(sizePolicy)
        self.SPED_ComboBox.setObjectName("SPED_ComboBox")
        self.verticalLayout_23.addWidget(self.SPED_ComboBox)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem8)
        self.horizontalLayout_12.addLayout(self.verticalLayout_23)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.CEST_Label = QtGui.QLabel(self.layoutWidget_5)
        self.CEST_Label.setObjectName("CEST_Label")
        self.horizontalLayout_13.addWidget(self.CEST_Label)
        self.Cest_Entry = QtGui.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cest_Entry.sizePolicy().hasHeightForWidth())
        self.Cest_Entry.setSizePolicy(sizePolicy)
        self.Cest_Entry.setObjectName("Cest_Entry")
        self.horizontalLayout_13.addWidget(self.Cest_Entry)
        self.NCM_Label = QtGui.QLabel(self.layoutWidget_5)
        self.NCM_Label.setObjectName("NCM_Label")
        self.horizontalLayout_13.addWidget(self.NCM_Label)
        self.NCM_Entry = QtGui.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NCM_Entry.sizePolicy().hasHeightForWidth())
        self.NCM_Entry.setSizePolicy(sizePolicy)
        self.NCM_Entry.setObjectName("NCM_Entry")
        self.horizontalLayout_13.addWidget(self.NCM_Entry)
        self.NBS_Label = QtGui.QLabel(self.layoutWidget_5)
        self.NBS_Label.setObjectName("NBS_Label")
        self.horizontalLayout_13.addWidget(self.NBS_Label)
        self.NBS_Entry = QtGui.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NBS_Entry.sizePolicy().hasHeightForWidth())
        self.NBS_Entry.setSizePolicy(sizePolicy)
        self.NBS_Entry.setObjectName("NBS_Entry")
        self.horizontalLayout_13.addWidget(self.NBS_Entry)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout_22.addLayout(self.horizontalLayout_12)
        self.splitter_6 = QtGui.QSplitter(self.splitter_7)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.layoutWidget = QtGui.QWidget(self.splitter_6)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ICMS_ISS_Label = QtGui.QLabel(self.layoutWidget)
        self.ICMS_ISS_Label.setObjectName("ICMS_ISS_Label")
        self.verticalLayout_5.addWidget(self.ICMS_ISS_Label)
        self.ICMS_Line = QtGui.QFrame(self.layoutWidget)
        self.ICMS_Line.setFrameShape(QtGui.QFrame.HLine)
        self.ICMS_Line.setFrameShadow(QtGui.QFrame.Sunken)
        self.ICMS_Line.setObjectName("ICMS_Line")
        self.verticalLayout_5.addWidget(self.ICMS_Line)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Origem_Label = QtGui.QLabel(self.layoutWidget)
        self.Origem_Label.setObjectName("Origem_Label")
        self.verticalLayout_13.addWidget(self.Origem_Label)
        self.Origem_ComboBox = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Origem_ComboBox.sizePolicy().hasHeightForWidth())
        self.Origem_ComboBox.setSizePolicy(sizePolicy)
        self.Origem_ComboBox.setObjectName("Origem_ComboBox")
        self.verticalLayout_13.addWidget(self.Origem_ComboBox)
        self.CSOSN_Label = QtGui.QLabel(self.layoutWidget)
        self.CSOSN_Label.setObjectName("CSOSN_Label")
        self.verticalLayout_13.addWidget(self.CSOSN_Label)
        self.CSOSN_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.CSOSN_ComboBox.setObjectName("CSOSN_ComboBox")
        self.verticalLayout_13.addWidget(self.CSOSN_ComboBox)
        self.ICMS_Label = QtGui.QLabel(self.layoutWidget)
        self.ICMS_Label.setObjectName("ICMS_Label")
        self.verticalLayout_13.addWidget(self.ICMS_Label)
        self.ICMS_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.ICMS_ComboBox.setObjectName("ICMS_ComboBox")
        self.verticalLayout_13.addWidget(self.ICMS_ComboBox)
        self.BaseST_Label = QtGui.QLabel(self.layoutWidget)
        self.BaseST_Label.setObjectName("BaseST_Label")
        self.verticalLayout_13.addWidget(self.BaseST_Label)
        self.BaseST_ComboBox = QtGui.QComboBox(self.layoutWidget)
        self.BaseST_ComboBox.setObjectName("BaseST_ComboBox")
        self.verticalLayout_13.addWidget(self.BaseST_ComboBox)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem9)
        self.horizontalLayout_17.addLayout(self.verticalLayout_13)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.BaseICMS_Label = QtGui.QLabel(self.layoutWidget)
        self.BaseICMS_Label.setObjectName("BaseICMS_Label")
        self.verticalLayout_16.addWidget(self.BaseICMS_Label)
        self.BaseICMS_Entry = QtGui.QLineEdit(self.layoutWidget)
        self.BaseICMS_Entry.setReadOnly(True)
        self.BaseICMS_Entry.setObjectName("BaseICMS_Entry")
        self.verticalLayout_16.addWidget(self.BaseICMS_Entry)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem10)
        self.horizontalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.splitter_3 = QtGui.QSplitter(self.splitter_6)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_4 = QtGui.QSplitter(self.splitter_3)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_5 = QtGui.QSplitter(self.splitter_4)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget_7 = QtGui.QWidget(self.splitter_5)
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.PIS_COFINS_Label = QtGui.QLabel(self.layoutWidget_7)
        self.PIS_COFINS_Label.setObjectName("PIS_COFINS_Label")
        self.verticalLayout_18.addWidget(self.PIS_COFINS_Label)
        self.PIS_COFINS_Line = QtGui.QFrame(self.layoutWidget_7)
        self.PIS_COFINS_Line.setFrameShape(QtGui.QFrame.HLine)
        self.PIS_COFINS_Line.setFrameShadow(QtGui.QFrame.Sunken)
        self.PIS_COFINS_Line.setObjectName("PIS_COFINS_Line")
        self.verticalLayout_18.addWidget(self.PIS_COFINS_Line)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.PIS_Label = QtGui.QLabel(self.layoutWidget_7)
        self.PIS_Label.setObjectName("PIS_Label")
        self.verticalLayout_26.addWidget(self.PIS_Label)
        self.PIS_ComboBox = QtGui.QComboBox(self.layoutWidget_7)
        self.PIS_ComboBox.setObjectName("PIS_ComboBox")
        self.verticalLayout_26.addWidget(self.PIS_ComboBox)
        self.COFINS_Label_2 = QtGui.QLabel(self.layoutWidget_7)
        self.COFINS_Label_2.setObjectName("COFINS_Label_2")
        self.verticalLayout_26.addWidget(self.COFINS_Label_2)
        self.COFINS_Label = QtGui.QComboBox(self.layoutWidget_7)
        self.COFINS_Label.setObjectName("COFINS_Label")
        self.verticalLayout_26.addWidget(self.COFINS_Label)
        self.verticalLayout_24.addLayout(self.verticalLayout_26)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.ReceitaPIS_Label = QtGui.QLabel(self.layoutWidget_7)
        self.ReceitaPIS_Label.setObjectName("ReceitaPIS_Label")
        self.verticalLayout_27.addWidget(self.ReceitaPIS_Label)
        self.ReceitaPIS_Entry = QtGui.QLineEdit(self.layoutWidget_7)
        self.ReceitaPIS_Entry.setObjectName("ReceitaPIS_Entry")
        self.verticalLayout_27.addWidget(self.ReceitaPIS_Entry)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem11)
        self.horizontalLayout_18.addLayout(self.verticalLayout_27)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.ReceitaCofins_Label = QtGui.QLabel(self.layoutWidget_7)
        self.ReceitaCofins_Label.setObjectName("ReceitaCofins_Label")
        self.verticalLayout_28.addWidget(self.ReceitaCofins_Label)
        self.ReceitaCofins_Entry = QtGui.QLineEdit(self.layoutWidget_7)
        self.ReceitaCofins_Entry.setObjectName("ReceitaCofins_Entry")
        self.verticalLayout_28.addWidget(self.ReceitaCofins_Entry)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem12)
        self.horizontalLayout_18.addLayout(self.verticalLayout_28)
        self.verticalLayout_24.addLayout(self.horizontalLayout_18)
        self.verticalLayout_17.addLayout(self.verticalLayout_24)
        self.layoutWidget_4 = QtGui.QWidget(self.splitter_7)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Others_Label = QtGui.QLabel(self.layoutWidget_4)
        self.Others_Label.setObjectName("Others_Label")
        self.verticalLayout_19.addWidget(self.Others_Label)
        self.Others_Line = QtGui.QFrame(self.layoutWidget_4)
        self.Others_Line.setFrameShape(QtGui.QFrame.HLine)
        self.Others_Line.setFrameShadow(QtGui.QFrame.Sunken)
        self.Others_Line.setObjectName("Others_Line")
        self.verticalLayout_19.addWidget(self.Others_Line)
        self.gridLayout_7.addLayout(self.verticalLayout_19, 0, 0, 1, 1)
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.DesconsiderarEAN_Label = QtGui.QLabel(self.layoutWidget_4)
        self.DesconsiderarEAN_Label.setObjectName("DesconsiderarEAN_Label")
        self.verticalLayout_37.addWidget(self.DesconsiderarEAN_Label)
        self.DesconsiderarEAN_ComboBox = QtGui.QComboBox(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesconsiderarEAN_ComboBox.sizePolicy().hasHeightForWidth())
        self.DesconsiderarEAN_ComboBox.setSizePolicy(sizePolicy)
        self.DesconsiderarEAN_ComboBox.setObjectName("DesconsiderarEAN_ComboBox")
        self.verticalLayout_37.addWidget(self.DesconsiderarEAN_ComboBox)
        self.gridLayout_7.addLayout(self.verticalLayout_37, 1, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(1200, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.splitter_7, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 250, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem14, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.TaxesWidget1, 0, 1, 1, 1)
        self.InputTabs.addTab(self.Taxes, "")
        self.SNGPC = QtGui.QWidget()
        self.SNGPC.setObjectName("SNGPC")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.SNGPC)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.SNGPC_Frame = QtGui.QFrame(self.SNGPC)
        self.SNGPC_Frame.setAutoFillBackground(True)
        self.SNGPC_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SNGPC_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.SNGPC_Frame.setObjectName("SNGPC_Frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.SNGPC_Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Reg_Label = QtGui.QLabel(self.SNGPC_Frame)
        self.Reg_Label.setObjectName("Reg_Label")
        self.horizontalLayout_5.addWidget(self.Reg_Label)
        self.Reg_Entry = QtGui.QLineEdit(self.SNGPC_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reg_Entry.sizePolicy().hasHeightForWidth())
        self.Reg_Entry.setSizePolicy(sizePolicy)
        self.Reg_Entry.setObjectName("Reg_Entry")
        self.horizontalLayout_5.addWidget(self.Reg_Entry)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.splitter_9 = QtGui.QSplitter(self.SNGPC_Frame)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.Nao_radioButton = QtGui.QRadioButton(self.splitter_9)
        self.Nao_radioButton.setChecked(True)
        self.Nao_radioButton.setAutoExclusive(True)
        self.Nao_radioButton.setObjectName("Nao_radioButton")
        self.Antibiotico_radioButton = QtGui.QRadioButton(self.splitter_9)
        self.Antibiotico_radioButton.setObjectName("Antibiotico_radioButton")
        self.ControleEspecial_radioButton = QtGui.QRadioButton(self.splitter_9)
        self.ControleEspecial_radioButton.setObjectName("ControleEspecial_radioButton")
        self.layoutWidget_3 = QtGui.QWidget(self.splitter_9)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_14 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Lista_Label = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lista_Label.sizePolicy().hasHeightForWidth())
        self.Lista_Label.setSizePolicy(sizePolicy)
        self.Lista_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.Lista_Label.setObjectName("Lista_Label")
        self.gridLayout_14.addWidget(self.Lista_Label, 0, 0, 1, 1)
        self.Adendo_Label = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Adendo_Label.sizePolicy().hasHeightForWidth())
        self.Adendo_Label.setSizePolicy(sizePolicy)
        self.Adendo_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.Adendo_Label.setObjectName("Adendo_Label")
        self.gridLayout_14.addWidget(self.Adendo_Label, 0, 1, 1, 1)
        self.UnidadeSNGPC_Label = QtGui.QLabel(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnidadeSNGPC_Label.sizePolicy().hasHeightForWidth())
        self.UnidadeSNGPC_Label.setSizePolicy(sizePolicy)
        self.UnidadeSNGPC_Label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.UnidadeSNGPC_Label.setObjectName("UnidadeSNGPC_Label")
        self.gridLayout_14.addWidget(self.UnidadeSNGPC_Label, 0, 2, 1, 1)
        self.Lista_ComboBox = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lista_ComboBox.sizePolicy().hasHeightForWidth())
        self.Lista_ComboBox.setSizePolicy(sizePolicy)
        self.Lista_ComboBox.setObjectName("Lista_ComboBox")
        self.gridLayout_14.addWidget(self.Lista_ComboBox, 1, 0, 1, 1)
        self.Adendo_ComboBox = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Adendo_ComboBox.sizePolicy().hasHeightForWidth())
        self.Adendo_ComboBox.setSizePolicy(sizePolicy)
        self.Adendo_ComboBox.setObjectName("Adendo_ComboBox")
        self.gridLayout_14.addWidget(self.Adendo_ComboBox, 1, 1, 1, 1)
        self.UnidadeSNGPC_ComboBox = QtGui.QComboBox(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UnidadeSNGPC_ComboBox.sizePolicy().hasHeightForWidth())
        self.UnidadeSNGPC_ComboBox.setSizePolicy(sizePolicy)
        self.UnidadeSNGPC_ComboBox.setObjectName("UnidadeSNGPC_ComboBox")
        self.gridLayout_14.addWidget(self.UnidadeSNGPC_ComboBox, 1, 2, 1, 1)
        self.gridLayout_12.addWidget(self.splitter_9, 0, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.splitter_8 = QtGui.QSplitter(self.SNGPC_Frame)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.SNGPC_Frame1 = QtGui.QFrame(self.splitter_8)
        self.SNGPC_Frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SNGPC_Frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.SNGPC_Frame1.setObjectName("SNGPC_Frame1")
        self.formLayout = QtGui.QFormLayout(self.SNGPC_Frame1)
        self.formLayout.setObjectName("formLayout")
        self.CapMedia_Label = QtGui.QLabel(self.SNGPC_Frame1)
        self.CapMedia_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CapMedia_Label.setObjectName("CapMedia_Label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.CapMedia_Label)
        self.CapMedia_Entry = QtGui.QLineEdit(self.SNGPC_Frame1)
        self.CapMedia_Entry.setMouseTracking(True)
        self.CapMedia_Entry.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.CapMedia_Entry.setStyleSheet("")
        self.CapMedia_Entry.setEchoMode(QtGui.QLineEdit.Normal)
        self.CapMedia_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.CapMedia_Entry.setReadOnly(False)
        self.CapMedia_Entry.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.CapMedia_Entry.setObjectName("CapMedia_Entry")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.CapMedia_Entry)
        self.Volume_Label = QtGui.QLabel(self.SNGPC_Frame1)
        self.Volume_Label.setObjectName("Volume_Label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.Volume_Label)
        self.Volume_Entry = QtGui.QLineEdit(self.SNGPC_Frame1)
        self.Volume_Entry.setStyleSheet("")
        self.Volume_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Volume_Entry.setReadOnly(False)
        self.Volume_Entry.setObjectName("Volume_Entry")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Volume_Entry)
        self.Concentracao_Label = QtGui.QLabel(self.SNGPC_Frame1)
        self.Concentracao_Label.setObjectName("Concentracao_Label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.Concentracao_Label)
        self.Concentracao_Entry = QtGui.QLineEdit(self.SNGPC_Frame1)
        self.Concentracao_Entry.setStyleSheet("")
        self.Concentracao_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Concentracao_Entry.setReadOnly(False)
        self.Concentracao_Entry.setObjectName("Concentracao_Entry")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Concentracao_Entry)
        self.UnidEmbalagemLabel = QtGui.QLabel(self.SNGPC_Frame1)
        self.UnidEmbalagemLabel.setObjectName("UnidEmbalagemLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.UnidEmbalagemLabel)
        self.UnidEmbalagem_Entry = QtGui.QLineEdit(self.SNGPC_Frame1)
        self.UnidEmbalagem_Entry.setStyleSheet("")
        self.UnidEmbalagem_Entry.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.UnidEmbalagem_Entry.setReadOnly(False)
        self.UnidEmbalagem_Entry.setObjectName("UnidEmbalagem_Entry")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.UnidEmbalagem_Entry)
        self.SNGPC_Frame2 = QtGui.QFrame(self.splitter_8)
        self.SNGPC_Frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SNGPC_Frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.SNGPC_Frame2.setObjectName("SNGPC_Frame2")
        self.formLayout_2 = QtGui.QFormLayout(self.SNGPC_Frame2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.DiasTrat_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.DiasTrat_Label.setObjectName("DiasTrat_Label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.DiasTrat_Label)
        self.DiasTrat_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.DiasTrat_Entry.setStyleSheet("")
        self.DiasTrat_Entry.setReadOnly(False)
        self.DiasTrat_Entry.setObjectName("DiasTrat_Entry")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.DiasTrat_Entry)
        self.Apres_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.Apres_Label.setObjectName("Apres_Label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.Apres_Label)
        self.Apres_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.Apres_Entry.setStyleSheet("")
        self.Apres_Entry.setReadOnly(False)
        self.Apres_Entry.setObjectName("Apres_Entry")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.Apres_Entry)
        self.NomeMedic_Label = QtGui.QLabel(self.SNGPC_Frame2)
        self.NomeMedic_Label.setObjectName("NomeMedic_Label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.NomeMedic_Label)
        self.NomeMedic_Entry = QtGui.QLineEdit(self.SNGPC_Frame2)
        self.NomeMedic_Entry.setStyleSheet("")
        self.NomeMedic_Entry.setReadOnly(False)
        self.NomeMedic_Entry.setObjectName("NomeMedic_Entry")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.NomeMedic_Entry)
        self.verticalLayout_8.addWidget(self.splitter_8)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem15, 1, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.SNGPC_Frame)
        self.InputTabs.addTab(self.SNGPC, "")
        self.BarCodes = QtGui.QWidget()
        self.BarCodes.setObjectName("BarCodes")
        self.lineEdit_8 = QtGui.QLineEdit(self.BarCodes)
        self.lineEdit_8.setGeometry(QtCore.QRect(270, 90, 133, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_8 = QtGui.QLabel(self.BarCodes)
        self.label_8.setGeometry(QtCore.QRect(218, 90, 46, 16))
        self.label_8.setObjectName("label_8")
        self.InputTabs.addTab(self.BarCodes, "")
        self.ProvCompCodes = QtGui.QWidget()
        self.ProvCompCodes.setObjectName("ProvCompCodes")
        self.lineEdit_9 = QtGui.QLineEdit(self.ProvCompCodes)
        self.lineEdit_9.setGeometry(QtCore.QRect(420, 120, 133, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_9 = QtGui.QLabel(self.ProvCompCodes)
        self.label_9.setGeometry(QtCore.QRect(368, 120, 46, 16))
        self.label_9.setObjectName("label_9")
        self.InputTabs.addTab(self.ProvCompCodes, "")
        self.verticalLayout_InputFrame.addWidget(self.InputTabs)
        self.gridLayout.addLayout(self.verticalLayout_InputFrame, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.InputFrame, 0, 0, 1, 1)
        ScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(ScrollArea)
        self.InputTabs.setCurrentIndex(3)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.Lista_ComboBox.setEnabled)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.SNGPC_Frame1.setEnabled)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.Lista_ComboBox.setEnabled)
        QtCore.QObject.connect(self.Nao_radioButton, QtCore.SIGNAL("toggled(bool)"), self.Lista_ComboBox.setDisabled)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.Adendo_ComboBox.setEnabled)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.SNGPC_Frame1.setEnabled)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.SNGPC_Frame2.setEnabled)
        QtCore.QObject.connect(self.Antibiotico_radioButton, QtCore.SIGNAL("clicked(bool)"), self.UnidadeSNGPC_ComboBox.setEnabled)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.SNGPC_Frame2.setEnabled)
        QtCore.QObject.connect(self.Nao_radioButton, QtCore.SIGNAL("toggled(bool)"), self.SNGPC_Frame2.setDisabled)
        QtCore.QObject.connect(self.Nao_radioButton, QtCore.SIGNAL("toggled(bool)"), self.UnidadeSNGPC_ComboBox.setDisabled)
        QtCore.QObject.connect(self.Nao_radioButton, QtCore.SIGNAL("toggled(bool)"), self.SNGPC_Frame1.setDisabled)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.Adendo_ComboBox.setEnabled)
        QtCore.QObject.connect(self.Nao_radioButton, QtCore.SIGNAL("toggled(bool)"), self.Adendo_ComboBox.setDisabled)
        QtCore.QObject.connect(self.ControleEspecial_radioButton, QtCore.SIGNAL("clicked(bool)"), self.UnidadeSNGPC_ComboBox.setEnabled)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("toggled(bool)"), self.SNGPC_Frame.setShown)
        QtCore.QObject.connect(self.SNGPC_Checkbox, QtCore.SIGNAL("pressed()"), self.SNGPC_Frame.show)
        QtCore.QMetaObject.connectSlotsByName(ScrollArea)

    def retranslateUi(self, ScrollArea):
        ScrollArea.setWindowTitle(QtGui.QApplication.translate("ScrollArea", "ScrollArea", None, QtGui.QApplication.UnicodeUTF8))
        self.Submit_Button.setText(QtGui.QApplication.translate("ScrollArea", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.Clear_Button.setText(QtGui.QApplication.translate("ScrollArea", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.Back_Button.setText(QtGui.QApplication.translate("ScrollArea", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("ScrollArea", "Whatvs1", None, QtGui.QApplication.UnicodeUTF8))
        self.Search_Button.setText(QtGui.QApplication.translate("ScrollArea", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("ScrollArea", "Whatvs2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("ScrollArea", "Whatvs3", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("ScrollArea", "Whatvs4", None, QtGui.QApplication.UnicodeUTF8))
        self.Product_Label_2.setText(QtGui.QApplication.translate("ScrollArea", "Produto", None, QtGui.QApplication.UnicodeUTF8))
        self.MedCheckBox_2.setText(QtGui.QApplication.translate("ScrollArea", "Medicamento", None, QtGui.QApplication.UnicodeUTF8))
        self.SNGPC_Checkbox.setText(QtGui.QApplication.translate("ScrollArea", "SNGPC", None, QtGui.QApplication.UnicodeUTF8))
        self.Type_ComboBox.setItemText(0, QtGui.QApplication.translate("ScrollArea", "Genérico", None, QtGui.QApplication.UnicodeUTF8))
        self.Type_ComboBox.setItemText(1, QtGui.QApplication.translate("ScrollArea", "Similar", None, QtGui.QApplication.UnicodeUTF8))
        self.Type_ComboBox.setItemText(2, QtGui.QApplication.translate("ScrollArea", "Referência", None, QtGui.QApplication.UnicodeUTF8))
        self.PrinAtiv_Label.setText(QtGui.QApplication.translate("ScrollArea", "Princípio Ativo", None, QtGui.QApplication.UnicodeUTF8))
        self.Descr_Label.setText(QtGui.QApplication.translate("ScrollArea", "Descrição Completa", None, QtGui.QApplication.UnicodeUTF8))
        self.Lab_Label.setText(QtGui.QApplication.translate("ScrollArea", "Laboratório", None, QtGui.QApplication.UnicodeUTF8))
        self.LabSearchButton.setToolTip(QtGui.QApplication.translate("ScrollArea", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.PrinAtivSearchButton.setToolTip(QtGui.QApplication.translate("ScrollArea", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab3Search.setToolTip(QtGui.QApplication.translate("ScrollArea", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab2Search.setToolTip(QtGui.QApplication.translate("ScrollArea", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Tab1Search.setToolTip(QtGui.QApplication.translate("ScrollArea", "<html><head/><body><p><img src=\":/NPX ICO/search.png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.TabAux1_Label.setText(QtGui.QApplication.translate("ScrollArea", "Tabela Aux1", None, QtGui.QApplication.UnicodeUTF8))
        self.Etiqueta_Label.setText(QtGui.QApplication.translate("ScrollArea", "Etiqueta Gôndula", None, QtGui.QApplication.UnicodeUTF8))
        self.TabAux2_Label.setText(QtGui.QApplication.translate("ScrollArea", "Tabela Aux2", None, QtGui.QApplication.UnicodeUTF8))
        self.TabAux3_Label.setText(QtGui.QApplication.translate("ScrollArea", "Tabela Aux3", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.Descricao), QtGui.QApplication.translate("ScrollArea", "Descrição", None, QtGui.QApplication.UnicodeUTF8))
        self.CostLastOrder.setText(QtGui.QApplication.translate("ScrollArea", "Custo Última Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.CostLastOrder_ST.setText(QtGui.QApplication.translate("ScrollArea", "Última Entrada + ST", None, QtGui.QApplication.UnicodeUTF8))
        self.PMC.setText(QtGui.QApplication.translate("ScrollArea", "Valor PMC", None, QtGui.QApplication.UnicodeUTF8))
        self.AllowDiscount_ComboBox.setItemText(0, QtGui.QApplication.translate("ScrollArea", "SIM", None, QtGui.QApplication.UnicodeUTF8))
        self.AllowDiscount_ComboBox.setItemText(1, QtGui.QApplication.translate("ScrollArea", "NÃO", None, QtGui.QApplication.UnicodeUTF8))
        self.AllowDiscount_Label.setText(QtGui.QApplication.translate("ScrollArea", "Permite Desconto na Venda?", None, QtGui.QApplication.UnicodeUTF8))
        self.CostPrice_Label.setText(QtGui.QApplication.translate("ScrollArea", "Preço de Custo", None, QtGui.QApplication.UnicodeUTF8))
        self.ProfitMargin_Label.setText(QtGui.QApplication.translate("ScrollArea", "Margem de Lucro(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.SellPrice_Label.setText(QtGui.QApplication.translate("ScrollArea", "Preço de Venda", None, QtGui.QApplication.UnicodeUTF8))
        self.Discount_Label.setText(QtGui.QApplication.translate("ScrollArea", "Desconto(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.MaxDiscount_Label.setText(QtGui.QApplication.translate("ScrollArea", "Desconto Max(%)", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_Label.setText(QtGui.QApplication.translate("ScrollArea", "Tipo de Preço de Custo Atualizado na Entr. Mercadoria", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(0, QtGui.QApplication.translate("ScrollArea", "VLR. UNITÁRIO BRUTO", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(1, QtGui.QApplication.translate("ScrollArea", "VLR. UNITÁRIO BRUTO + ST", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(2, QtGui.QApplication.translate("ScrollArea", "VLR. UNITÁRIO BRUTO + ST + IPI", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(3, QtGui.QApplication.translate("ScrollArea", "VLR. UNITÁRIO LÍQUIDO", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(4, QtGui.QApplication.translate("ScrollArea", "VLR. UNITÁRIO LÍQUIDO + ST", None, QtGui.QApplication.UnicodeUTF8))
        self.PriceCostType_ComboBox.setItemText(5, QtGui.QApplication.translate("ScrollArea", "VLR. UNITÁRIO LÍQUIDO + ST + IPI", None, QtGui.QApplication.UnicodeUTF8))
        self.LastPriceDate.setDisplayFormat(QtGui.QApplication.translate("ScrollArea", "dd/mm/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.LastPriceDate_Label.setText(QtGui.QApplication.translate("ScrollArea", "Última Alteração de Preço", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.Price), QtGui.QApplication.translate("ScrollArea", "Preço", None, QtGui.QApplication.UnicodeUTF8))
        self.SPED_Label.setText(QtGui.QApplication.translate("ScrollArea", "Tipo SPED", None, QtGui.QApplication.UnicodeUTF8))
        self.CEST_Label.setText(QtGui.QApplication.translate("ScrollArea", "Classif. CEST", None, QtGui.QApplication.UnicodeUTF8))
        self.NCM_Label.setText(QtGui.QApplication.translate("ScrollArea", "Classif. Fiscal/NCM", None, QtGui.QApplication.UnicodeUTF8))
        self.NBS_Label.setText(QtGui.QApplication.translate("ScrollArea", "Código NBS", None, QtGui.QApplication.UnicodeUTF8))
        self.ICMS_ISS_Label.setText(QtGui.QApplication.translate("ScrollArea", "ICMS/ISS", None, QtGui.QApplication.UnicodeUTF8))
        self.Origem_Label.setText(QtGui.QApplication.translate("ScrollArea", "Origem", None, QtGui.QApplication.UnicodeUTF8))
        self.CSOSN_Label.setText(QtGui.QApplication.translate("ScrollArea", "CSOSN/CST ICMS", None, QtGui.QApplication.UnicodeUTF8))
        self.ICMS_Label.setText(QtGui.QApplication.translate("ScrollArea", "Alíq. ICMS/ISS", None, QtGui.QApplication.UnicodeUTF8))
        self.BaseST_Label.setText(QtGui.QApplication.translate("ScrollArea", "Tipo Base ST", None, QtGui.QApplication.UnicodeUTF8))
        self.BaseICMS_Label.setText(QtGui.QApplication.translate("ScrollArea", "Red. Base ICMS (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.PIS_COFINS_Label.setText(QtGui.QApplication.translate("ScrollArea", "PIS/COFINS", None, QtGui.QApplication.UnicodeUTF8))
        self.PIS_Label.setText(QtGui.QApplication.translate("ScrollArea", "CST PIS", None, QtGui.QApplication.UnicodeUTF8))
        self.COFINS_Label_2.setText(QtGui.QApplication.translate("ScrollArea", "CST COFINS", None, QtGui.QApplication.UnicodeUTF8))
        self.ReceitaPIS_Label.setText(QtGui.QApplication.translate("ScrollArea", "Natur. Receita PIS", None, QtGui.QApplication.UnicodeUTF8))
        self.ReceitaCofins_Label.setText(QtGui.QApplication.translate("ScrollArea", "Natur. Receita COFINS", None, QtGui.QApplication.UnicodeUTF8))
        self.Others_Label.setText(QtGui.QApplication.translate("ScrollArea", "Outros", None, QtGui.QApplication.UnicodeUTF8))
        self.DesconsiderarEAN_Label.setText(QtGui.QApplication.translate("ScrollArea", "Desconsiderar Cód. Barras na Geração NFC-e/NF-e/CF-e", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.Taxes), QtGui.QApplication.translate("ScrollArea", "Tributação", None, QtGui.QApplication.UnicodeUTF8))
        self.Reg_Label.setText(QtGui.QApplication.translate("ScrollArea", "Reg. Ministério da Saúde", None, QtGui.QApplication.UnicodeUTF8))
        self.Nao_radioButton.setText(QtGui.QApplication.translate("ScrollArea", "Não", None, QtGui.QApplication.UnicodeUTF8))
        self.Antibiotico_radioButton.setText(QtGui.QApplication.translate("ScrollArea", "Antibióticos", None, QtGui.QApplication.UnicodeUTF8))
        self.ControleEspecial_radioButton.setText(QtGui.QApplication.translate("ScrollArea", "Controle Especial", None, QtGui.QApplication.UnicodeUTF8))
        self.Lista_Label.setText(QtGui.QApplication.translate("ScrollArea", "Lista", None, QtGui.QApplication.UnicodeUTF8))
        self.Adendo_Label.setText(QtGui.QApplication.translate("ScrollArea", "Adendo", None, QtGui.QApplication.UnicodeUTF8))
        self.UnidadeSNGPC_Label.setText(QtGui.QApplication.translate("ScrollArea", "Unidade SNGPC", None, QtGui.QApplication.UnicodeUTF8))
        self.CapMedia_Label.setText(QtGui.QApplication.translate("ScrollArea", "Cap. Média (ML)", None, QtGui.QApplication.UnicodeUTF8))
        self.Volume_Label.setText(QtGui.QApplication.translate("ScrollArea", "Volume(ML)", None, QtGui.QApplication.UnicodeUTF8))
        self.Concentracao_Label.setText(QtGui.QApplication.translate("ScrollArea", "Concentração(MG)", None, QtGui.QApplication.UnicodeUTF8))
        self.UnidEmbalagemLabel.setText(QtGui.QApplication.translate("ScrollArea", "Unid. por Embalagem", None, QtGui.QApplication.UnicodeUTF8))
        self.DiasTrat_Label.setText(QtGui.QApplication.translate("ScrollArea", "Dias Tratamento", None, QtGui.QApplication.UnicodeUTF8))
        self.Apres_Label.setText(QtGui.QApplication.translate("ScrollArea", "Apres./Concentr.", None, QtGui.QApplication.UnicodeUTF8))
        self.NomeMedic_Label.setText(QtGui.QApplication.translate("ScrollArea", "Nome Medicamento", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.SNGPC), QtGui.QApplication.translate("ScrollArea", "SNGPC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ScrollArea", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.BarCodes), QtGui.QApplication.translate("ScrollArea", "Código de Barras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("ScrollArea", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.InputTabs.setTabText(self.InputTabs.indexOf(self.ProvCompCodes), QtGui.QApplication.translate("ScrollArea", "Código Fornecedor", None, QtGui.QApplication.UnicodeUTF8))

import npx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ScrollArea = QtGui.QScrollArea()
    ui = Ui_ScrollArea()
    ui.setupUi(ScrollArea)
    ScrollArea.show()
    sys.exit(app.exec_())

