# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guilh\Desktop\NewPharmaExperience\npx_mock\src\GUI\LabInput.ui'
#
# Created: Mon Apr  2 18:21:03 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LabInput(QtGui.QWidget):
    def __init__(self, master):
        QtGui.QWidget.__init__(self,master)
        self.gridLayout_10 = QtGui.QGridLayout(self)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.LabFrame = QtGui.QFrame(self)
        self.LabFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.LabFrame.setObjectName("LabFrame")
        self.gridLayout_3 = QtGui.QGridLayout(self.LabFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TitleLabel = QtGui.QLabel(self.LabFrame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_3.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.LogoLabel = QtGui.QLabel(self.LabFrame)
        self.LogoLabel.setObjectName("LogoLabel")
        self.gridLayout_3.addWidget(self.LogoLabel, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.LabFrame)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ButtonWidget = QtGui.QWidget(self.groupBox)
        self.ButtonWidget.setObjectName("ButtonWidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.ButtonWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.SalvarButton = QtGui.QPushButton(self.ButtonWidget)
        self.SalvarButton.setObjectName("SalvarButton")
        self.gridLayout_5.addWidget(self.SalvarButton, 0, 1, 1, 1)
        self.CancelarButton = QtGui.QPushButton(self.ButtonWidget)
        self.CancelarButton.setObjectName("CancelarButton")
        self.gridLayout_5.addWidget(self.CancelarButton, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(1100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.ButtonWidget, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 800, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.InputWidget = QtGui.QWidget(self.groupBox)
        self.InputWidget.setObjectName("InputWidget")
        self.gridLayout = QtGui.QGridLayout(self.InputWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.EnderLabel_2 = QtGui.QLabel(self.InputWidget)
        self.EnderLabel_2.setMinimumSize(QtCore.QSize(0, 0))
        self.EnderLabel_2.setObjectName("EnderLabel_2")
        self.gridLayout.addWidget(self.EnderLabel_2, 1, 0, 1, 1)
        self.EnderEntry_2 = QtGui.QLineEdit(self.InputWidget)
        self.EnderEntry_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.EnderEntry_2.setObjectName("EnderEntry_2")
        self.gridLayout.addWidget(self.EnderEntry_2, 1, 1, 1, 1)
        self.FaxEntry = QtGui.QLineEdit(self.InputWidget)
        self.FaxEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FaxEntry.setObjectName("FaxEntry")
        self.gridLayout.addWidget(self.FaxEntry, 4, 1, 1, 1)
        self.NameEntry = QtGui.QLineEdit(self.InputWidget)
        self.NameEntry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.NameEntry.setObjectName("NameEntry")
        self.gridLayout.addWidget(self.NameEntry, 0, 1, 1, 1)
        self.Email2Entry = QtGui.QLineEdit(self.InputWidget)
        self.Email2Entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Email2Entry.setObjectName("Email2Entry")
        self.gridLayout.addWidget(self.Email2Entry, 3, 1, 1, 1)
        self.Phone1Label = QtGui.QLabel(self.InputWidget)
        self.Phone1Label.setMinimumSize(QtCore.QSize(0, 0))
        self.Phone1Label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Phone1Label.setObjectName("Phone1Label")
        self.gridLayout.addWidget(self.Phone1Label, 2, 2, 1, 1)
        self.Email1Label = QtGui.QLabel(self.InputWidget)
        self.Email1Label.setMinimumSize(QtCore.QSize(0, 0))
        self.Email1Label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Email1Label.setObjectName("Email1Label")
        self.gridLayout.addWidget(self.Email1Label, 2, 0, 1, 1)
        self.Phone2Entry = QtGui.QLineEdit(self.InputWidget)
        self.Phone2Entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Phone2Entry.setObjectName("Phone2Entry")
        self.gridLayout.addWidget(self.Phone2Entry, 3, 3, 1, 1)
        self.Email1Entry = QtGui.QLineEdit(self.InputWidget)
        self.Email1Entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Email1Entry.setObjectName("Email1Entry")
        self.gridLayout.addWidget(self.Email1Entry, 2, 1, 1, 1)
        self.Phone2Label = QtGui.QLabel(self.InputWidget)
        self.Phone2Label.setMinimumSize(QtCore.QSize(0, 0))
        self.Phone2Label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Phone2Label.setObjectName("Phone2Label")
        self.gridLayout.addWidget(self.Phone2Label, 3, 2, 1, 1)
        self.Phone1Entry = QtGui.QLineEdit(self.InputWidget)
        self.Phone1Entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Phone1Entry.setObjectName("Phone1Entry")
        self.gridLayout.addWidget(self.Phone1Entry, 2, 3, 1, 1)
        self.Email2Label = QtGui.QLabel(self.InputWidget)
        self.Email2Label.setMinimumSize(QtCore.QSize(0, 0))
        self.Email2Label.setMaximumSize(QtCore.QSize(45, 16777215))
        self.Email2Label.setObjectName("Email2Label")
        self.gridLayout.addWidget(self.Email2Label, 3, 0, 1, 1)
        self.CNPJLabel = QtGui.QLabel(self.InputWidget)
        self.CNPJLabel.setObjectName("CNPJLabel")
        self.gridLayout.addWidget(self.CNPJLabel, 0, 2, 1, 1)
        self.CNPJEntry = QtGui.QLineEdit(self.InputWidget)
        self.CNPJEntry.setMaximumSize(QtCore.QSize(200, 16777215))
        self.CNPJEntry.setObjectName("CNPJEntry")
        self.gridLayout.addWidget(self.CNPJEntry, 0, 3, 1, 1)
        self.NameLabel = QtGui.QLabel(self.InputWidget)
        self.NameLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.NameLabel.setObjectName("NameLabel")
        self.gridLayout.addWidget(self.NameLabel, 0, 0, 1, 1)
        self.FaxLabel = QtGui.QLabel(self.InputWidget)
        self.FaxLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.FaxLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FaxLabel.setObjectName("FaxLabel")
        self.gridLayout.addWidget(self.FaxLabel, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.InputWidget, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.gridLayout_10.addWidget(self.LabFrame, 0, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, LabInput):
        self.TitleLabel.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p align=\"center\">Cadastro de Laboratório</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.LogoLabel.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p><img src=\":/NPX ICO/clinic (2).png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.SalvarButton.setText(QtGui.QApplication.translate("LabInput", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelarButton.setText(QtGui.QApplication.translate("LabInput", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.EnderLabel_2.setText(QtGui.QApplication.translate("LabInput", "Endereço", None, QtGui.QApplication.UnicodeUTF8))
        self.Phone1Label.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p>Telefone 1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Email1Label.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p>E-mail 1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Phone2Label.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p>Telefone 2</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Email2Label.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p>E-mail 2</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.CNPJLabel.setText(QtGui.QApplication.translate("LabInput", "CNPJ", None, QtGui.QApplication.UnicodeUTF8))
        self.NameLabel.setText(QtGui.QApplication.translate("LabInput", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.FaxLabel.setText(QtGui.QApplication.translate("LabInput", "<html><head/><body><p>Fax</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

from src.GUI import npx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    LabInput = QtGui.QFrame()
    ui = Ui_LabInput()
    ui.setupUi(LabInput)
    LabInput.show()
    sys.exit(app.exec_())
