# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\guilh\Desktop\NewPharmaExperience\npx_mock\src\GUI\FrameFrame.ui'
#
# Created: Sat Mar 31 00:37:38 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_StartPage(QtGui.QWidget):
    def __init__(self, master):
        QtGui.QWidget.__init__(self,master)
        self.gridLayout = QtGui.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(self)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtGui.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.calendarWidget = QtGui.QCalendarWidget(self.frame)
        self.calendarWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_8.addWidget(self.calendarWidget, 2, 2, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 2, 1, 1)
        self.MenuPlaceFrame = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenuPlaceFrame.sizePolicy().hasHeightForWidth())
        self.MenuPlaceFrame.setSizePolicy(sizePolicy)
        self.MenuPlaceFrame.setMinimumSize(QtCore.QSize(125, 290))
        self.MenuPlaceFrame.setMaximumSize(QtCore.QSize(125, 16777215))
        self.MenuPlaceFrame.setAutoFillBackground(True)
        self.MenuPlaceFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MenuPlaceFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MenuPlaceFrame.setObjectName("MenuPlaceFrame")
        self.Relatorios_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Relatorios_Frame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        self.Relatorios_Frame.setAutoFillBackground(True)
        self.Relatorios_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Relatorios_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Relatorios_Frame.setObjectName("Relatorios_Frame")
        self.gridLayout_10 = QtGui.QGridLayout(self.Relatorios_Frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.RelatoriosMenu = QtGui.QGroupBox(self.Relatorios_Frame)
        self.RelatoriosMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RelatoriosMenu.sizePolicy().hasHeightForWidth())
        self.RelatoriosMenu.setSizePolicy(sizePolicy)
        self.RelatoriosMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.RelatoriosMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.RelatoriosMenu.setFont(font)
        self.RelatoriosMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.RelatoriosMenu.setObjectName("RelatoriosMenu")
        self.gridLayout_11 = QtGui.QGridLayout(self.RelatoriosMenu)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.RelatClie_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatClie_Button.setFont(font)
        self.RelatClie_Button.setObjectName("RelatClie_Button")
        self.gridLayout_11.addWidget(self.RelatClie_Button, 3, 0, 1, 1)
        self.RelatEsto_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatEsto_Button.setFont(font)
        self.RelatEsto_Button.setObjectName("RelatEsto_Button")
        self.gridLayout_11.addWidget(self.RelatEsto_Button, 2, 0, 1, 1)
        self.RelatPlacHold1_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatPlacHold1_Button.setFont(font)
        self.RelatPlacHold1_Button.setObjectName("RelatPlacHold1_Button")
        self.gridLayout_11.addWidget(self.RelatPlacHold1_Button, 6, 0, 1, 1)
        self.RelatVend_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatVend_Button.setFont(font)
        self.RelatVend_Button.setObjectName("RelatVend_Button")
        self.gridLayout_11.addWidget(self.RelatVend_Button, 0, 0, 1, 1)
        self.RelatBack_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatBack_Button.setFont(font)
        self.RelatBack_Button.setObjectName("RelatBack_Button")
        self.gridLayout_11.addWidget(self.RelatBack_Button, 5, 0, 1, 1)
        self.RelatComp_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatComp_Button.setFont(font)
        self.RelatComp_Button.setObjectName("RelatComp_Button")
        self.gridLayout_11.addWidget(self.RelatComp_Button, 1, 0, 1, 1)
        self.RelatPlacHold2_Button = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatPlacHold2_Button.setFont(font)
        self.RelatPlacHold2_Button.setObjectName("RelatPlacHold2_Button")
        self.gridLayout_11.addWidget(self.RelatPlacHold2_Button, 7, 0, 1, 1)
        self.RelatPlacHold2_Button_2 = QtGui.QPushButton(self.RelatoriosMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.RelatPlacHold2_Button_2.setFont(font)
        self.RelatPlacHold2_Button_2.setObjectName("RelatPlacHold2_Button_2")
        self.gridLayout_11.addWidget(self.RelatPlacHold2_Button_2, 8, 0, 1, 1)
        self.gridLayout_10.addWidget(self.RelatoriosMenu, 0, 0, 1, 1)
        self.Saida_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Saida_Frame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        self.Saida_Frame.setAutoFillBackground(True)
        self.Saida_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Saida_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Saida_Frame.setObjectName("Saida_Frame")
        self.gridLayout_14 = QtGui.QGridLayout(self.Saida_Frame)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.SaidaMenu = QtGui.QGroupBox(self.Saida_Frame)
        self.SaidaMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaidaMenu.sizePolicy().hasHeightForWidth())
        self.SaidaMenu.setSizePolicy(sizePolicy)
        self.SaidaMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.SaidaMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.SaidaMenu.setFont(font)
        self.SaidaMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.SaidaMenu.setObjectName("SaidaMenu")
        self.gridLayout_15 = QtGui.QGridLayout(self.SaidaMenu)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.SaidOutr_Button = QtGui.QPushButton(self.SaidaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.SaidOutr_Button.setFont(font)
        self.SaidOutr_Button.setObjectName("SaidOutr_Button")
        self.gridLayout_15.addWidget(self.SaidOutr_Button, 3, 0, 1, 1)
        self.Vencidos_Button = QtGui.QPushButton(self.SaidaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Vencidos_Button.setFont(font)
        self.Vencidos_Button.setObjectName("Vencidos_Button")
        self.gridLayout_15.addWidget(self.Vencidos_Button, 0, 0, 1, 1)
        self.UsoInt_Button = QtGui.QPushButton(self.SaidaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.UsoInt_Button.setFont(font)
        self.UsoInt_Button.setObjectName("UsoInt_Button")
        self.gridLayout_15.addWidget(self.UsoInt_Button, 1, 0, 1, 1)
        self.SaidBack_Button = QtGui.QPushButton(self.SaidaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.SaidBack_Button.setFont(font)
        self.SaidBack_Button.setObjectName("SaidBack_Button")
        self.gridLayout_15.addWidget(self.SaidBack_Button, 6, 0, 1, 1)
        self.Transf_Button = QtGui.QPushButton(self.SaidaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Transf_Button.setFont(font)
        self.Transf_Button.setObjectName("Transf_Button")
        self.gridLayout_15.addWidget(self.Transf_Button, 2, 0, 1, 1)
        self.gridLayout_14.addWidget(self.SaidaMenu, 0, 0, 1, 1)
        self.Gerencia_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Gerencia_Frame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        self.Gerencia_Frame.setAutoFillBackground(True)
        self.Gerencia_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Gerencia_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Gerencia_Frame.setObjectName("Gerencia_Frame")
        self.gridLayout_16 = QtGui.QGridLayout(self.Gerencia_Frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.GerenciaMenu = QtGui.QGroupBox(self.Gerencia_Frame)
        self.GerenciaMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GerenciaMenu.sizePolicy().hasHeightForWidth())
        self.GerenciaMenu.setSizePolicy(sizePolicy)
        self.GerenciaMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.GerenciaMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.GerenciaMenu.setFont(font)
        self.GerenciaMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.GerenciaMenu.setObjectName("GerenciaMenu")
        self.gridLayout_17 = QtGui.QGridLayout(self.GerenciaMenu)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.Ger_Button1 = QtGui.QPushButton(self.GerenciaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Ger_Button1.setFont(font)
        self.Ger_Button1.setObjectName("Ger_Button1")
        self.gridLayout_17.addWidget(self.Ger_Button1, 0, 0, 1, 1)
        self.GereBack_Button = QtGui.QPushButton(self.GerenciaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.GereBack_Button.setFont(font)
        self.GereBack_Button.setObjectName("GereBack_Button")
        self.gridLayout_17.addWidget(self.GereBack_Button, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.GerenciaMenu, 0, 0, 1, 1)
        self.Entrada_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Entrada_Frame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        self.Entrada_Frame.setAutoFillBackground(True)
        self.Entrada_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Entrada_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Entrada_Frame.setObjectName("Entrada_Frame")
        self.gridLayout_12 = QtGui.QGridLayout(self.Entrada_Frame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.EntradasMenu = QtGui.QGroupBox(self.Entrada_Frame)
        self.EntradasMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EntradasMenu.sizePolicy().hasHeightForWidth())
        self.EntradasMenu.setSizePolicy(sizePolicy)
        self.EntradasMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.EntradasMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.EntradasMenu.setFont(font)
        self.EntradasMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.EntradasMenu.setObjectName("EntradasMenu")
        self.gridLayout_13 = QtGui.QGridLayout(self.EntradasMenu)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.NFe_Button = QtGui.QPushButton(self.EntradasMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.NFe_Button.setFont(font)
        self.NFe_Button.setObjectName("NFe_Button")
        self.gridLayout_13.addWidget(self.NFe_Button, 0, 0, 1, 1)
        self.EntraBack_Button = QtGui.QPushButton(self.EntradasMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.EntraBack_Button.setFont(font)
        self.EntraBack_Button.setObjectName("EntraBack_Button")
        self.gridLayout_13.addWidget(self.EntraBack_Button, 3, 0, 1, 1)
        self.NF_Button = QtGui.QPushButton(self.EntradasMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.NF_Button.setFont(font)
        self.NF_Button.setObjectName("NF_Button")
        self.gridLayout_13.addWidget(self.NF_Button, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.EntradasMenu, 0, 0, 1, 1)
        self.Cadastro_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Cadastro_Frame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        self.Cadastro_Frame.setAutoFillBackground(True)
        self.Cadastro_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Cadastro_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Cadastro_Frame.setObjectName("Cadastro_Frame")
        self.gridLayout_4 = QtGui.QGridLayout(self.Cadastro_Frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CadastroMenu = QtGui.QGroupBox(self.Cadastro_Frame)
        self.CadastroMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CadastroMenu.sizePolicy().hasHeightForWidth())
        self.CadastroMenu.setSizePolicy(sizePolicy)
        self.CadastroMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.CadastroMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.CadastroMenu.setFont(font)
        self.CadastroMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.CadastroMenu.setObjectName("CadastroMenu")
        self.gridLayout_5 = QtGui.QGridLayout(self.CadastroMenu)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Produto_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Produto_Button.setFont(font)
        self.Produto_Button.setObjectName("Produto_Button")
        self.gridLayout_5.addWidget(self.Produto_Button, 0, 0, 1, 1)
        self.Placeholder1_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Placeholder1_Button.setFont(font)
        self.Placeholder1_Button.setObjectName("Placeholder1_Button")
        self.gridLayout_5.addWidget(self.Placeholder1_Button, 6, 0, 1, 1)
        self.Clientes_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Clientes_Button.setFont(font)
        self.Clientes_Button.setObjectName("Clientes_Button")
        self.gridLayout_5.addWidget(self.Clientes_Button, 3, 0, 1, 1)
        self.Distribuidor_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Distribuidor_Button.setFont(font)
        self.Distribuidor_Button.setObjectName("Distribuidor_Button")
        self.gridLayout_5.addWidget(self.Distribuidor_Button, 2, 0, 1, 1)
        self.Laboratorios_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Laboratorios_Button.setFont(font)
        self.Laboratorios_Button.setObjectName("Laboratorios_Button")
        self.gridLayout_5.addWidget(self.Laboratorios_Button, 1, 0, 1, 1)
        self.Placeholder2_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Placeholder2_Button.setFont(font)
        self.Placeholder2_Button.setObjectName("Placeholder2_Button")
        self.gridLayout_5.addWidget(self.Placeholder2_Button, 7, 0, 1, 1)
        self.CadaBack_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.CadaBack_Button.setFont(font)
        self.CadaBack_Button.setObjectName("CadaBack_Button")
        self.gridLayout_5.addWidget(self.CadaBack_Button, 5, 0, 1, 1)
        self.TabelasAux_Button = QtGui.QPushButton(self.CadastroMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.TabelasAux_Button.setFont(font)
        self.TabelasAux_Button.setObjectName("TabelasAux_Button")
        self.gridLayout_5.addWidget(self.TabelasAux_Button, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.CadastroMenu, 0, 0, 1, 1)
        self.Sistema_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Sistema_Frame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        self.Sistema_Frame.setAutoFillBackground(True)
        self.Sistema_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Sistema_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Sistema_Frame.setObjectName("Sistema_Frame")
        self.gridLayout_18 = QtGui.QGridLayout(self.Sistema_Frame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.SistemaMenu = QtGui.QGroupBox(self.Sistema_Frame)
        self.SistemaMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SistemaMenu.sizePolicy().hasHeightForWidth())
        self.SistemaMenu.setSizePolicy(sizePolicy)
        self.SistemaMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.SistemaMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.SistemaMenu.setFont(font)
        self.SistemaMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.SistemaMenu.setObjectName("SistemaMenu")
        self.gridLayout_19 = QtGui.QGridLayout(self.SistemaMenu)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.SistConfig_Button = QtGui.QPushButton(self.SistemaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.SistConfig_Button.setFont(font)
        self.SistConfig_Button.setObjectName("SistConfig_Button")
        self.gridLayout_19.addWidget(self.SistConfig_Button, 2, 0, 1, 1)
        self.SistUsu_Button = QtGui.QPushButton(self.SistemaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.SistUsu_Button.setFont(font)
        self.SistUsu_Button.setObjectName("SistUsu_Button")
        self.gridLayout_19.addWidget(self.SistUsu_Button, 0, 0, 1, 1)
        self.SistBack_Button = QtGui.QPushButton(self.SistemaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.SistBack_Button.setFont(font)
        self.SistBack_Button.setObjectName("SistBack_Button")
        self.gridLayout_19.addWidget(self.SistBack_Button, 4, 0, 1, 1)
        self.SistAtua_Button = QtGui.QPushButton(self.SistemaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(7)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.SistAtua_Button.setFont(font)
        self.SistAtua_Button.setObjectName("SistAtua_Button")
        self.gridLayout_19.addWidget(self.SistAtua_Button, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.SistemaMenu, 0, 0, 1, 1)
        self.Consulta_Frame = QtGui.QFrame(self.MenuPlaceFrame)
        self.Consulta_Frame.setGeometry(QtCore.QRect(0, 0, 119, 287))
        self.Consulta_Frame.setAutoFillBackground(True)
        self.Consulta_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Consulta_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Consulta_Frame.setObjectName("Consulta_Frame")
        self.gridLayout_6 = QtGui.QGridLayout(self.Consulta_Frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ConsultaMenu = QtGui.QGroupBox(self.Consulta_Frame)
        self.ConsultaMenu.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConsultaMenu.sizePolicy().hasHeightForWidth())
        self.ConsultaMenu.setSizePolicy(sizePolicy)
        self.ConsultaMenu.setMinimumSize(QtCore.QSize(10, 0))
        self.ConsultaMenu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.ConsultaMenu.setFont(font)
        self.ConsultaMenu.setAlignment(QtCore.Qt.AlignCenter)
        self.ConsultaMenu.setObjectName("ConsultaMenu")
        self.gridLayout_7 = QtGui.QGridLayout(self.ConsultaMenu)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ClieCons_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.ClieCons_Button.setFont(font)
        self.ClieCons_Button.setObjectName("ClieCons_Button")
        self.gridLayout_7.addWidget(self.ClieCons_Button, 3, 0, 1, 1)
        self.DistCons_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.DistCons_Button.setFont(font)
        self.DistCons_Button.setObjectName("DistCons_Button")
        self.gridLayout_7.addWidget(self.DistCons_Button, 2, 0, 1, 1)
        self.PlacHoldCons_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.PlacHoldCons_Button.setFont(font)
        self.PlacHoldCons_Button.setObjectName("PlacHoldCons_Button")
        self.gridLayout_7.addWidget(self.PlacHoldCons_Button, 6, 0, 1, 1)
        self.ProdCons_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.ProdCons_Button.setFont(font)
        self.ProdCons_Button.setObjectName("ProdCons_Button")
        self.gridLayout_7.addWidget(self.ProdCons_Button, 0, 0, 1, 1)
        self.BackCons_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.BackCons_Button.setFont(font)
        self.BackCons_Button.setObjectName("BackCons_Button")
        self.gridLayout_7.addWidget(self.BackCons_Button, 5, 0, 1, 1)
        self.LabCons_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.LabCons_Button.setFont(font)
        self.LabCons_Button.setObjectName("LabCons_Button")
        self.gridLayout_7.addWidget(self.LabCons_Button, 1, 0, 1, 1)
        self.PlacHoldCons2_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.PlacHoldCons2_Button.setFont(font)
        self.PlacHoldCons2_Button.setObjectName("PlacHoldCons2_Button")
        self.gridLayout_7.addWidget(self.PlacHoldCons2_Button, 7, 0, 1, 1)
        self.PlacHoldCons3_Button = QtGui.QPushButton(self.ConsultaMenu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.PlacHoldCons3_Button.setFont(font)
        self.PlacHoldCons3_Button.setObjectName("PlacHoldCons3_Button")
        self.gridLayout_7.addWidget(self.PlacHoldCons3_Button, 8, 0, 1, 1)
        self.gridLayout_6.addWidget(self.ConsultaMenu, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.MenuPlaceFrame, 1, 2, 1, 1)
        self.MainMenuFrame = QtGui.QFrame(self.MenuPlaceFrame)
        self.MainMenuFrame.setGeometry(QtCore.QRect(0, 0, 120, 287))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainMenuFrame.sizePolicy().hasHeightForWidth())
        self.MainMenuFrame.setSizePolicy(sizePolicy)
        self.MainMenuFrame.setAutoFillBackground(True)
        self.MainMenuFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.MainMenuFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.MainMenuFrame.setObjectName("MainMenuFrame")
        self.gridLayout_3 = QtGui.QGridLayout(self.MainMenuFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MenuBox = QtGui.QGroupBox(self.MainMenuFrame)
        self.MenuBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenuBox.sizePolicy().hasHeightForWidth())
        self.MenuBox.setSizePolicy(sizePolicy)
        self.MenuBox.setMinimumSize(QtCore.QSize(10, 0))
        self.MenuBox.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(True)
        font.setStrikeOut(False)
        font.setBold(True)
        self.MenuBox.setFont(font)
        self.MenuBox.setAlignment(QtCore.Qt.AlignCenter)
        self.MenuBox.setObjectName("MenuBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.MenuBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Cadastro_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Cadastro_Button.setFont(font)
        self.Cadastro_Button.setObjectName("Cadastro_Button")
        self.gridLayout_2.addWidget(self.Cadastro_Button, 0, 0, 1, 1)
        self.Sistema_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Sistema_Button.setFont(font)
        self.Sistema_Button.setObjectName("Sistema_Button")
        self.gridLayout_2.addWidget(self.Sistema_Button, 6, 0, 1, 1)
        self.Entradas_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Entradas_Button.setFont(font)
        self.Entradas_Button.setObjectName("Entradas_Button")
        self.gridLayout_2.addWidget(self.Entradas_Button, 3, 0, 1, 1)
        self.Relatorios_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Relatorios_Button.setFont(font)
        self.Relatorios_Button.setObjectName("Relatorios_Button")
        self.gridLayout_2.addWidget(self.Relatorios_Button, 2, 0, 1, 1)
        self.Consulta_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Consulta_Button.setFont(font)
        self.Consulta_Button.setObjectName("Consulta_Button")
        self.gridLayout_2.addWidget(self.Consulta_Button, 1, 0, 1, 1)
        self.PlacHoldMenu_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.PlacHoldMenu_Button.setFont(font)
        self.PlacHoldMenu_Button.setObjectName("PlacHoldMenu_Button")
        self.gridLayout_2.addWidget(self.PlacHoldMenu_Button, 7, 0, 1, 1)
        self.Gerencia_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Gerencia_Button.setFont(font)
        self.Gerencia_Button.setObjectName("Gerencia_Button")
        self.gridLayout_2.addWidget(self.Gerencia_Button, 5, 0, 1, 1)
        self.Saidas_Button = QtGui.QPushButton(self.MenuBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.Saidas_Button.setFont(font)
        self.Saidas_Button.setObjectName("Saidas_Button")
        self.gridLayout_2.addWidget(self.Saidas_Button, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.MenuBox, 0, 2, 1, 1)
        self.VendasDiarias = QtGui.QGroupBox(self.frame)
        self.VendasDiarias.setObjectName("VendasDiarias")
        self.label_8 = QtGui.QLabel(self.VendasDiarias)
        self.label_8.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.VendasDiarias)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.VendasDiarias)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.VendasDiarias)
        self.label_11.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.VendasDiarias)
        self.label_12.setGeometry(QtCore.QRect(20, 110, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.VendasDiarias)
        self.label_13.setGeometry(QtCore.QRect(100, 30, 71, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.VendasDiarias)
        self.label_14.setGeometry(QtCore.QRect(100, 50, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.VendasDiarias)
        self.label_15.setGeometry(QtCore.QRect(100, 70, 71, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.VendasDiarias)
        self.label_16.setGeometry(QtCore.QRect(100, 90, 71, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.VendasDiarias)
        self.label_17.setGeometry(QtCore.QRect(100, 110, 71, 16))
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.VendasDiarias, 2, 5, 3, 1)
        self.VendasMes = QtGui.QGroupBox(self.frame)
        self.VendasMes.setMinimumSize(QtCore.QSize(80, 160))
        self.VendasMes.setObjectName("VendasMes")
        self.label_2 = QtGui.QLabel(self.VendasMes)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.VendasMes)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.VendasMes)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.VendasMes)
        self.label_5.setGeometry(QtCore.QRect(100, 70, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.VendasMes)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.VendasMes)
        self.label_7.setGeometry(QtCore.QRect(100, 110, 121, 16))
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.VendasMes, 2, 4, 3, 1)
        self.ProxPgtos = QtGui.QGroupBox(self.frame)
        self.ProxPgtos.setObjectName("ProxPgtos")
        self.label_18 = QtGui.QLabel(self.ProxPgtos)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.ProxPgtos)
        self.label_19.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.ProxPgtos)
        self.label_20.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.ProxPgtos)
        self.label_21.setGeometry(QtCore.QRect(20, 120, 111, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.ProxPgtos)
        self.label_22.setGeometry(QtCore.QRect(150, 30, 91, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.ProxPgtos)
        self.label_23.setGeometry(QtCore.QRect(130, 60, 91, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.ProxPgtos)
        self.label_24.setGeometry(QtCore.QRect(130, 90, 91, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.ProxPgtos)
        self.label_25.setGeometry(QtCore.QRect(140, 120, 91, 16))
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.ProxPgtos, 2, 6, 3, 1)
        self.graphicsView = QtGui.QGraphicsView(self.frame)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_8.addWidget(self.graphicsView, 0, 4, 2, 3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QObject.connect(self.Cadastro_Button, QtCore.SIGNAL("clicked()"), self.Cadastro_Frame.raise_)
        QtCore.QObject.connect(self.CadaBack_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.GereBack_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.Consulta_Button, QtCore.SIGNAL("clicked()"), self.Consulta_Frame.raise_)
        QtCore.QObject.connect(self.Relatorios_Button, QtCore.SIGNAL("clicked()"), self.Relatorios_Frame.raise_)
        QtCore.QObject.connect(self.Entradas_Button, QtCore.SIGNAL("clicked()"), self.Entrada_Frame.raise_)
        QtCore.QObject.connect(self.SistBack_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.Sistema_Button, QtCore.SIGNAL("clicked()"), self.Sistema_Frame.raise_)
        QtCore.QObject.connect(self.Gerencia_Button, QtCore.SIGNAL("clicked()"), self.Gerencia_Frame.raise_)
        QtCore.QObject.connect(self.BackCons_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.EntraBack_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.RelatBack_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.SaidBack_Button, QtCore.SIGNAL("clicked()"), self.MainMenuFrame.raise_)
        QtCore.QObject.connect(self.Saidas_Button, QtCore.SIGNAL("clicked()"), self.Saida_Frame.raise_)
        #self.Produto_Button.clicked.connect(lambda: ctrl.show_frame(Ui_InputPage) )
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, parent):
        #self.parent.setWindowTitle(QtGui.QApplication.translate("parent", "parent", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("parent", "<html><head/><body><p><img src=\":/NPX ICO/clinic (2).png\"/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatoriosMenu.setTitle(QtGui.QApplication.translate("parent", "Relatórios", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatClie_Button.setText(QtGui.QApplication.translate("parent", "Clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatEsto_Button.setText(QtGui.QApplication.translate("parent", "Estoque", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatPlacHold1_Button.setText(QtGui.QApplication.translate("parent", "Placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatVend_Button.setText(QtGui.QApplication.translate("parent", "Vendas", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatBack_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatComp_Button.setText(QtGui.QApplication.translate("parent", "Compras", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatPlacHold2_Button.setText(QtGui.QApplication.translate("parent", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.RelatPlacHold2_Button_2.setText(QtGui.QApplication.translate("parent", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.SaidaMenu.setTitle(QtGui.QApplication.translate("parent", "Saídas", None, QtGui.QApplication.UnicodeUTF8))
        self.SaidOutr_Button.setText(QtGui.QApplication.translate("parent", "Outras", None, QtGui.QApplication.UnicodeUTF8))
        self.Vencidos_Button.setText(QtGui.QApplication.translate("parent", "Vencidos", None, QtGui.QApplication.UnicodeUTF8))
        self.UsoInt_Button.setText(QtGui.QApplication.translate("parent", "Uso Interno", None, QtGui.QApplication.UnicodeUTF8))
        self.SaidBack_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.Transf_Button.setText(QtGui.QApplication.translate("parent", "Transferência", None, QtGui.QApplication.UnicodeUTF8))
        self.GerenciaMenu.setTitle(QtGui.QApplication.translate("parent", "Gerência", None, QtGui.QApplication.UnicodeUTF8))
        self.Ger_Button1.setText(QtGui.QApplication.translate("parent", "Produto", None, QtGui.QApplication.UnicodeUTF8))
        self.GereBack_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.EntradasMenu.setTitle(QtGui.QApplication.translate("parent", "Entradas", None, QtGui.QApplication.UnicodeUTF8))
        self.NFe_Button.setText(QtGui.QApplication.translate("parent", "NFe", None, QtGui.QApplication.UnicodeUTF8))
        self.EntraBack_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.NF_Button.setText(QtGui.QApplication.translate("parent", "NF Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.CadastroMenu.setTitle(QtGui.QApplication.translate("parent", "Cadastro", None, QtGui.QApplication.UnicodeUTF8))
        self.Produto_Button.setText(QtGui.QApplication.translate("parent", "Produto", None, QtGui.QApplication.UnicodeUTF8))
        self.Placeholder1_Button.setText(QtGui.QApplication.translate("parent", "Placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.Clientes_Button.setText(QtGui.QApplication.translate("parent", "Clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.Distribuidor_Button.setText(QtGui.QApplication.translate("parent", "Distribuidor", None, QtGui.QApplication.UnicodeUTF8))
        self.Laboratorios_Button.setText(QtGui.QApplication.translate("parent", "Laboratórios", None, QtGui.QApplication.UnicodeUTF8))
        self.Placeholder2_Button.setText(QtGui.QApplication.translate("parent", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.CadaBack_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.TabelasAux_Button.setText(QtGui.QApplication.translate("parent", "Tabelas Aux", None, QtGui.QApplication.UnicodeUTF8))
        self.SistemaMenu.setTitle(QtGui.QApplication.translate("parent", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.SistConfig_Button.setText(QtGui.QApplication.translate("parent", "Configurações", None, QtGui.QApplication.UnicodeUTF8))
        self.SistUsu_Button.setText(QtGui.QApplication.translate("parent", "Usuários", None, QtGui.QApplication.UnicodeUTF8))
        self.SistBack_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.SistAtua_Button.setText(QtGui.QApplication.translate("parent", "Atualizações", None, QtGui.QApplication.UnicodeUTF8))
        self.MenuBox.setTitle(QtGui.QApplication.translate("parent", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.Cadastro_Button.setText(QtGui.QApplication.translate("parent", "Cadastro", None, QtGui.QApplication.UnicodeUTF8))
        self.Sistema_Button.setText(QtGui.QApplication.translate("parent", "Sistema", None, QtGui.QApplication.UnicodeUTF8))
        self.Entradas_Button.setText(QtGui.QApplication.translate("parent", "Entradas", None, QtGui.QApplication.UnicodeUTF8))
        self.Relatorios_Button.setText(QtGui.QApplication.translate("parent", "Relatórios", None, QtGui.QApplication.UnicodeUTF8))
        self.Consulta_Button.setText(QtGui.QApplication.translate("parent", "Consulta", None, QtGui.QApplication.UnicodeUTF8))
        self.PlacHoldMenu_Button.setText(QtGui.QApplication.translate("parent", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.Gerencia_Button.setText(QtGui.QApplication.translate("parent", "Gerência", None, QtGui.QApplication.UnicodeUTF8))
        self.Saidas_Button.setText(QtGui.QApplication.translate("parent", "Saídas", None, QtGui.QApplication.UnicodeUTF8))
        self.ConsultaMenu.setTitle(QtGui.QApplication.translate("parent", "Consulta", None, QtGui.QApplication.UnicodeUTF8))
        self.ClieCons_Button.setText(QtGui.QApplication.translate("parent", "Clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.DistCons_Button.setText(QtGui.QApplication.translate("parent", "Distribuidor", None, QtGui.QApplication.UnicodeUTF8))
        self.PlacHoldCons_Button.setText(QtGui.QApplication.translate("parent", "Placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.ProdCons_Button.setText(QtGui.QApplication.translate("parent", "Produto", None, QtGui.QApplication.UnicodeUTF8))
        self.BackCons_Button.setText(QtGui.QApplication.translate("parent", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.LabCons_Button.setText(QtGui.QApplication.translate("parent", "Laboratórios", None, QtGui.QApplication.UnicodeUTF8))
        self.PlacHoldCons2_Button.setText(QtGui.QApplication.translate("parent", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.PlacHoldCons3_Button.setText(QtGui.QApplication.translate("parent", "PlaceHolder", None, QtGui.QApplication.UnicodeUTF8))
        self.VendasDiarias.setTitle(QtGui.QApplication.translate("parent", "Próximos Pagamentos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("parent", "Boleto 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("parent", "Boleto 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("parent", "Boleto 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("parent", "Boleto 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("parent", "Boleto 5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("parent", "21/12/1957", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("parent", "21/12/1957", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("parent", "21/12/1957", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("parent", "21/12/1957", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("parent", "21/12/1957", None, QtGui.QApplication.UnicodeUTF8))
        self.VendasMes.setTitle(QtGui.QApplication.translate("parent", "Vendas do Dia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("parent", "Atendimentos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("parent", "Valor total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("parent", "(Número de vendas)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("parent", "(Soma das Vendas)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("parent", "Variação diária:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("parent", "(VendaHj/VendaOntem)", None, QtGui.QApplication.UnicodeUTF8))
        self.ProxPgtos.setTitle(QtGui.QApplication.translate("parent", "Valor de Vendas no Mês", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("parent", "Total de Vendas:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("parent", "Valor das Vendas:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("parent", "Total de Compras:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("parent", "Razão Venda/Compra:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("parent", "(453)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("parent", "(R$ 54000.00)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("parent", "(R$ 23000.00)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("parent", "(234.78%)", None, QtGui.QApplication.UnicodeUTF8))

import npx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    parent = QtGui.QFrame()
    ctrl=0
    ui = Ui_StartPage(parent,ctrl)
    #ui.setupUi(parent)
    parent.show()
    sys.exit(app.exec_())
